README.md

Resolves #9.
Inspected results on github.
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] I have updated the documentation accordingly.

Minor metadata usage example fix.

---

pom.xml

Keep current with upstream ffmpeg
Just a version bump. However it probably does enable new functionality because of all the upstream changes.
Build, run unit tests, start view application.
No problems noted.

Upgrade to ffmpeg 4.2.1

---

viewer/src/main/java/org/jmisb/viewer/MisbViewer.java

Resolves #20 by adding as-needed scroll bars to the metadata panel in the viewer.
Wrapped the existing panel in a JScrollPane
Tested locally with a MISB file that generates a lot of entries.

Add scroll bars to viewer metadata panel

---

api/pom.xml
api/src/test/java/org/jmisb/api/klv/st0601/PlatformRollAngleTest.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorRelativeAzimuthTest.java
api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkAltitudeTest.java
core/pom.xml
pom.xml
viewer/pom.xml

Resolves #27.
Also includes some minor test improvements that I used to validate the coverage reporting
Adds jacoco maven plugin.
Ran tests, added more tests, checked results.

Add test coverage checks to maven build

---

api/src/main/java/org/jmisb/api/klv/st0601/IcingDetected.java
api/src/main/java/org/jmisb/api/klv/st0601/OperationalMode.java
api/src/main/java/org/jmisb/api/klv/st0601/PlatformStatus.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/main/java/org/jmisb/api/klv/st0601/UasEnumeration.java
api/src/test/java/org/jmisb/api/klv/st0601/IcingDetectedTest.java
api/src/test/java/org/jmisb/api/klv/st0601/OperationalModeTest.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformStatusTest.java

Adds additional ST0601 data types, currently handed as Opaque.
These are all enumeration types, and share common code.
Unit tests added.

Add support for Icing Detected, Operational Mode and Platform Status

---

api/src/main/java/org/jmisb/api/klv/st0601/PlatformAngleOfAttack.java
api/src/main/java/org/jmisb/api/klv/st0601/PlatformSideslipAngle.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkAngle.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformAngleOfAttackTest.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformSideslipAngleTest.java

Adds support for a couple of missing tags (50, 52).
This is represented the same as Platform Pitch Angle, so implemented using shared code.
Implemented unit tests.
Used viewer application to check that values appear with test data from MISB (e.g. HD_MP2_06011_TS_ASYN_V1_001.mpg)

Add support for Platform Angle of Attack and Sideslip Angle.

---

api/src/main/java/org/jmisb/api/klv/st0601/SensorEastVelocity.java
api/src/main/java/org/jmisb/api/klv/st0601/SensorNorthVelocity.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkSensorVelocity.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorEastVelocityTest.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorNorthVelocityTest.java

Adds support for Tags 79 and 80, using shared code.
Adds usual support classes.

Add support for Sensor North Velocity and East Velocity

---

api/src/main/java/org/jmisb/api/klv/st0601/SensorControlMode.java
api/src/main/java/org/jmisb/api/klv/st0601/SensorFieldOfViewName.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorControlModeTest.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorFieldOfViewNameTest.java

These are the last of the unsupported enumerations for ST0601.
Implemented

Add support for Sensor Control Mode and Sensor Field of View Name

---

api/src/main/java/org/jmisb/api/klv/st0601/RelativeHumidity.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/RelativeHumidityTest.java

Adds support for an unimplemented tag - Relative Humidity
Fairly standard implementation + changes to factory and unit tests.

Add support for Relative Humidity.

---

api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkStringTest.java

No functional changes.
Improves test coverage - we don't have a instantiate-via-factory test for this tag.

Add unit test for Platform Tail Number

---

api/src/main/java/org/jmisb/api/klv/st0601/AlternatePlatformHeading.java
api/src/main/java/org/jmisb/api/klv/st0601/PlatformMagneticHeading.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkAngle360.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/main/java/org/jmisb/api/klv/st0601/WindDirectionAngle.java
api/src/test/java/org/jmisb/api/klv/st0601/AlternatePlatformHeadingTest.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformMagneticHeadingTest.java

Adds implementation for two tags - 64 and 71.
These have different semantics but equivalent implementation to the existing Wind Direction Angle and Platform Heading Angle values, so now share a superclass.
Unit tests with good coverage.
Viewer application for Platform Magnetic Heading, Alternate Platform Heading, Wind Direction and  Platform Heading Angle based on MISB test files.

Implement Alternate Platform Heading and Platform Magnetic Heading.

---

api/src/main/java/org/jmisb/api/klv/st0601/OutsideAirTemperature.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/OutsideAirTemperatureTest.java

Adds support for Outside Air Temperature (Tag 39).
Adds standard UasDatalinkValue implementation, updates factory and includes unit tests.
Unit tests, plus ran MISB HD_MP2_06011_TS_SYN_V1_001.mpg test file to verify.

Implement Outside Air Temperature support.

---

api/src/main/java/org/jmisb/api/klv/st0601/PlatformVerticalSpeed.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformVerticalSpeedTest.java

Adds support for missing tag.
Fairly standard UasDatalinkValue implementation, plus tests and factory method change.
Unit tests plus viewer application on MISB test file that uses this tag.

Add support for platform vertical speed (tag 51).

---

api/src/main/java/org/jmisb/api/klv/st0601/PlatformFuelRemaining.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformFuelRemainingTest.java

Adds support for a missing ST0601 tag.
Fairly standard IUasDatalinkValue implementation. Includes unit tests and factory method updates.
Unit tests. Viewer application on MISB test data that uses this tag.

Implement Platform Fuel Remaining (Tag 58).

---

api/src/main/java/org/jmisb/api/klv/st0601/LaserPrfCode.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/LaserPrfCodeTest.java

Adds support for a tag we don't yet have
Fairly standard IUasDatalinkValue implementation, plus tests and factory method change.
Unit tests added as part of this change, and viewer application on a MISB test file that uses this tag.

Implement Laser PRF Code (Tag 62)

---

api/src/main/java/org/jmisb/api/klv/st0601/AlternatePlatformAltitude.java
api/src/main/java/org/jmisb/api/klv/st0601/AlternatePlatformEllipsoidHeight.java
api/src/main/java/org/jmisb/api/klv/st0601/DensityAltitude.java
api/src/main/java/org/jmisb/api/klv/st0601/FrameCenterElevation.java
api/src/main/java/org/jmisb/api/klv/st0601/FrameCenterHae.java
api/src/main/java/org/jmisb/api/klv/st0601/SensorEllipsoidHeight.java
api/src/main/java/org/jmisb/api/klv/st0601/TargetLocationElevation.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkAltitude.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkAltitudeTest.java

Adds support for a couple of tags we previously didn't support (75 and 76).
Just a couple more subclasses for UasDatalinkAltitude. Most of the change is in documentation 
(including some similar subclasses) and unit tests.

Add Sensor and Alternative Platform Ellipsoid Heights

---

api/src/main/java/org/jmisb/api/klv/st0601/NavsatsInView.java
api/src/main/java/org/jmisb/api/klv/st0601/PositioningMethodSource.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/NavsatsInViewTest.java
api/src/test/java/org/jmisb/api/klv/st0601/PositioningMethodSourceTest.java

Adds support for tags that were previously handled as opaque.
Implements IUasDatalinkValue for those tags, tests and factory method changes.
Unit testing only. I think these tags are newer than my test data.

Navigation Source and Satellite count (Tags 123 / 124)

---

api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkStringTest.java

Picks up a change to the ST0601.16 test that was previously wrong
Updates test. We already had the right encoding as a string.

update TargetId test to reflect ST0601.16 change

---

README.md

Updates documentation to refer to the recent implementation of ST1204.
Docs only.
N/A
N/A

Minor update to readme to include ST1204

---

api/src/main/java/org/jmisb/api/klv/st0601/PlatformSideslipAngleFull.java
api/src/test/java/org/jmisb/api/klv/st0601/PlatformSideslipAngleFullTest.java

Resolves #63.
Updates range to be -180/180 (was -90/90). Revises tests, including a new test case that was added to ST0601.16.
N/A

Update PlatformSideslipAngleFull implementation

---

api/src/main/java/org/jmisb/api/klv/st0601/PlatformStatus.java

This removes a comment that is no longer valid, since ST0601.16 has been revised to fix the typo.
Comment removal.
Just unit tests.
N/A.

Remove comment about typo, source documentation fixed

---

api/src/main/java/org/jmisb/api/klv/st0601/SensorFieldOfViewName.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorFieldOfViewNameTest.java

This was added in ST0601.16.
Relates to #52 .
Extend enumeration and add related unit tests.
N/A.

Add Continuous Zoom to Sensor Field of View name implementation.

---

api/src/test/java/org/jmisb/api/klv/st0601/SensorEastVelocityTest.java

Previously there was no test case for Tag 80, and we used the one from Sensor North Velocity (Tag 79).
This removes the duplicate test and adds the Tag 80 test values.
Update to the test case.

Update Sensor East Velocity test case to reflect ST0601.16 change.

---

api/src/main/java/org/jmisb/api/klv/st0601/AlternatePlatformEllipsoidHeightExtended.java
api/src/main/java/org/jmisb/api/klv/st0601/AlternatePlatformLongitude.java
api/src/main/java/org/jmisb/api/klv/st0601/CornerOffset.java
api/src/main/java/org/jmisb/api/klv/st0601/DensityAltitudeExtended.java
api/src/main/java/org/jmisb/api/klv/st0601/FullCornerLatitude.java
api/src/main/java/org/jmisb/api/klv/st0601/FullCornerLongitude.java
api/src/main/java/org/jmisb/api/klv/st0601/SensorEllipsoidHeightExtended.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/test/java/org/jmisb/api/klv/st0601/AlternatePlatformEllipsoidHeightExtendedTest.java
api/src/test/java/org/jmisb/api/klv/st0601/CornerOffsetTest.java
api/src/test/java/org/jmisb/api/klv/st0601/DensityAltitudeExtendedTest.java
api/src/test/java/org/jmisb/api/klv/st0601/SensorEllipsoidHeightExtendedTest.java
api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkLatitudeTest.java
api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkLongitudeTest.java

This is important when using them in a list or tree (e.g. view application metadata window) because
otherwise you can end up with several "Corner" values, all different but indistinguishable.
The change is mostly mechanical, although it does change some constructor signatures. That could be avoided by keeping the old signatures and just adding new constructors, but the behaviour wouldn't be consistent.
Added a little javadoc where it was previously only on the superclass.
Because I was in the CornerOffset and Full Corner lat/lon areas updating tests, I also included the revised test cases for those, see #52 
Just unit tests.

Modify display names to be unique per tag.

---

api/src/main/java/org/jmisb/api/klv/st0601/ActiveWavelengthList.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/main/java/org/jmisb/api/klv/st0601/WavelengthsList.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/Wavelengths.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/package-info.java
api/src/test/java/org/jmisb/api/klv/st0601/ActiveWavelengthListTest.java
api/src/test/java/org/jmisb/api/klv/st0601/WavelengthsListTest.java

Implements two closely related tags that we didn't previously support.
Usual IUasDatalinkValue implementation, although slight difference to parsing and generation logic because of the list (DLP/VLP) structures.
Introduces a new module providing POJO support for the packed structures. Only one class there for now, but more expected as we work through the rest of the tags.
Unit tests. Should be no impact on any existing code.
N/A.

Implement Active Wavelength List and Wavelengths List (ST0601 Tag 121 and 128)

---

api/src/test/java/org/jmisb/api/klv/st0601/NestedSecurityMetadataTest.java

Just some missing test coverage. I thought I had most of these, but clearly missed on.
Also minor test refactoring. No main/ side changes.
Adds one test case, makes testing common.

Add test for UasDatalinkFactory creation of NestedSecurityMetadata

---

api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/WaypointList.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/Location.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/Waypoint.java
api/src/test/java/org/jmisb/api/klv/st0601/WaypointListTest.java

Implements an unsupported tag.
Fairly standard IUasMetadataValue implementation. Adds a couple of data transfer objects to represent the underlying data model.

Implement Waypoint List (ST0601 Tag 141)

---

api/src/main/java/org/jmisb/api/klv/st0601/LaserPrfCode.java
api/src/test/java/org/jmisb/api/klv/st0601/LaserPrfCodeTest.java

Resolves #62 
Adds an additional check to the "from value" constructor, and tests to match.
Also makes change to existing checks to verify that we're getting the right (meaningful) exception message.
Unit tests. I also ran the viewer application to check it still showed this tag value (although that isn't very meaningful, because that constructor isn't used for the display case).

Implement additional PRF Laser Code check

---

api/src/main/java/org/jmisb/api/klv/st0601/PayloadList.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/Payload.java
api/src/test/java/org/jmisb/api/klv/st0601/PayloadListTest.java
api/src/test/java/org/jmisb/api/klv/st0601/dto/PayloadTest.java

Implements a tag we don't yet support. This isn't very useful without Tag 139, but its a step in the right direction.
Fairly standard IUasDatalink implementation. Adds a new data transfer object for the Payload.

Implement Payload List (ST0601 Tag 138)

---

api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java

Fixes a forgotten javadoc update for the WaypointList
No code changes - docs only.
Build with unit tests.
N/A

Minor javadoc for the WaypointList tag

---

.github/ISSUE_TEMPLATE/task.md

Provides a github issues template for maintenance tasks that aren't really bugs or feature requests, but just "chores".
Resolves #77.
Adds a basic template.
I merged this on my repo, and enabled issues. Seems OK.

Add Github Task Template

---

pom.xml

Upgrades the ffmpeg version we rely on to the latest (14 April 2020) release. Keeps the technical debt down.
Just updates the maven dependency.
Full build and unit tests. All pass.
Ran some sample videos through the viewer application. No changes / issues noted.
N/A.

Upgrade to ffmpeg 4.2.2-1.5.3

---

api/src/test/java/org/jmisb/api/klv/st0903/VmtiMetadataConstantsTest.java

It doesn't really do anything other than get test coverage for that module to 100%.
Adds trivial test case. No code changes.
Unit test.
(assuming that test coverage counts as an "issue").

Add trivial test for VMTI constants

---

api/src/main/java/org/jmisb/api/video/VideoFileOutput.java

See #119. This sets the stream ID to 0xBD (corresponding to async metadata).
Creates a side data element (based on reading the FFMPEG source code).
Not sure about this allocation approach (using BytePointer), would appreciate guidance on that.
Tested by inspection of the Integration Test results, running through CMITT, and a commercial viewer.
No unit tests, although that would be good.
I'm not yet sure how to unit test this.

Initial attempt at setting metadata stream ID

---

api/src/test/java/org/jmisb/api/video/VideoFileInputOutputIT.java

Changes the VideoFileInputOutputIT object country code value to use the correct type (and therefore the right encoding).
Updates test.
Re-ran unit tests.

Fix Object Country Code value type for integration test.

---

api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkConstants.java
api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkConstantsTest.java

Reflect the current (.16) version of this standard.
Modifies the applicable constant, and adds a test to increase test coverage.

Bump ST_VERSION_NUMBER to match ST0601.16

---

api/src/main/java/org/jmisb/api/klv/st0601/ActivePayloads.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/test/java/org/jmisb/api/klv/st0601/ActivePayloadsTest.java

Implements a tag we don't yet support.
Usual IUasDatalinkValue implementation. This one is an arbitrary length bit array, which I implemented using BigInteger. That might be overkill, but made the implementation pretty easy.

Implement Active Payloads (ST0601 Tag 139)

---

api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java
api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
api/src/main/java/org/jmisb/api/klv/st0601/WeaponsStores.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/WeaponStore.java
api/src/main/java/org/jmisb/api/klv/st0601/dto/WeaponStoreStatus.java
api/src/test/java/org/jmisb/api/klv/st0601/WeaponsStoresTest.java
api/src/test/java/org/jmisb/api/klv/st0601/dto/WeaponStoreStatusTest.java

Adds support for a tag we don't yet support.
The implementation is similar to other IUasDatalinkValue instantiations, although there are a couple of corner cases around the way the status works. I think I have those covered off in unit testing.
This one also has a bit more javadoc than normal, based on some supporting advice from MISB.
Only unit tests.
N/A.

Implement ST0601 Tag 140 - WeaponsStores

---

api/src/test/java/org/jmisb/api/klv/st0601/dto/WavelengthsTest.java

Just improves test coverage. No executable changes.
Adds a couple of unit tests.
N/A.

Improve test coverage for Wavelengths class

---

api/src/main/java/org/jmisb/api/klv/st0903/shared/Confidence.java
api/src/main/java/org/jmisb/api/klv/st0903/shared/VmtiUtf8.java
api/src/main/java/org/jmisb/api/klv/st0903/vmask/PixelRunPair.java
api/src/test/java/org/jmisb/api/klv/st1204/CoreIdentifierTortureTest.java
api/src/test/java/org/jmisb/api/klv/st1204/IdTypeTest.java

Janitorial cleanups for some headers.
No code changes, just deletes some template headers that I shouldn't have committed.
Just re-ran unit tests.
N/A

Minor header cleanups

---

api/src/main/java/org/jmisb/api/klv/eg0104/PredatorUavMessage.java

While looking at other fixes, I noted a stray debug output in the unit tests.
Removes a `System.out.println()` debug entry from the `PredatorUavMessage.java` code.
Re-ran unit tests.

Remove debug println() from EG0104 implementation

---

api/src/main/java/org/jmisb/api/klv/st1204/CoreIdentifier.java
api/src/main/java/org/jmisb/api/klv/st1204/IdType.java
api/src/main/java/org/jmisb/api/klv/st1204/package-info.java

There were some issues in the ST1204 package level javadoc (I think I cut-n-pasted from firefox's PDF browser, and spaces got lost). I started on a little cleanup of ST1204 javadocs, including those problems.
Just updates the javadoc, and fixes some formatting.
Inspected the generated results.

st1204: update documentation

---

README.md

The work under #152 didn't quite look as well as I'd hoped on merge. It turns out the "autolink" feature only works on conversations: https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls
Uses real links instead of just numbers for issues in the table. 
Also had one incorrect link.
Checked links now work. The rendering doesn't look right yet - I hope that'll be fixed when it gets into the main repo, but even still, live links are better than just a number.

readme: additional cleanups

---

.github/workflows/macos.yml

This is adds an additional build target to the CI configuration for MacOS. If this works out, I'll probably add windows and maybe other linux configurations. I don't yet know if its possible to get an easy android build.
No code changes - it uses github actions to run on PR and push to the `develop` branch.
I ran it in my fork. Seems OK.

Add github action for MacOS build.

---

.github/workflows/windows.yml

We declare priority platforms in README.md - this adds one more to the CI checks.
Resolves #157. 
Github action that is closely based on macos build.
Will test via this PR. No code changes.

add windows build to push and PR checks

---

pom.xml

As part of implementing #177 , I got notification about this. 
Upgrades from 2.13.1 to 2.13.3 (which is current).
Ran viewer app - checked normal functionality, plus that we get some errors logged for known-problematic files.
N/A.

viewer: update log4j version

---

pom.xml

Just routine maintenance on the build system.
Resolves #177. 
Upgrades OWASP Dependency Check plugin (for maven). Currently we have 5.3.0, and current is 5.3.2.
Ran several builds with this enabled (`-Pdependencycheck`), inspected results.
N/A.

build: upgrade Dependency Check analyser to 5.3.2

---

api/src/main/java/org/jmisb/api/klv/st1909/OverlayRendererConfiguration.java

This is the javadoc cleanup / completion for the ST1909 package.
One additional method doc.
Just build / unit tests.

st1909: update javadoc

---

api/checkstyle_suppressions.xml
api/src/main/java/org/jmisb/api/klv/st1201/DecodeResult.java
api/src/main/java/org/jmisb/api/klv/st1201/FpEncoder.java
api/src/main/java/org/jmisb/api/klv/st1201/package-info.java

Updates and extends javadoc in ST1201 implementation to fix checkstyle warnings.
Resolves #192.
Update javadoc - some new method descriptions, some style fixes.
Enables warnings (removes supression) for this package.
Build / unit test only.
N/A.

st1201: update javadoc

---

api/checkstyle_suppressions.xml
api/src/main/java/org/jmisb/api/common/InvalidDataHandler.java
api/src/main/java/org/jmisb/api/common/KlvParseException.java
api/src/main/java/org/jmisb/api/common/LogOnInvalidDataStrategy.java
api/src/main/java/org/jmisb/api/common/ThrowOnInvalidDataStrategy.java
api/src/main/java/org/jmisb/api/common/package-info.java
api/src/main/java/org/jmisb/api/klv/eg0104/PredatorMetadataConstants.java

This addresses the last of the javadoc warnings from checkstyle
Adds missing methods and style fixes.
Removes suppressions.
Build only.

clean up remaining javadoc warnings

---

api/pom.xml
examples/README.md
examples/pom.xml
examples/systemout/README.md
examples/systemout/pom.xml
examples/systemout/src/main/java/org/jmisb/examples/systemout/Main.java
examples/systemout/src/main/java/org/jmisb/examples/systemout/MetadataPlayer.java
examples/systemout/src/main/java/org/jmisb/examples/systemout/PrintOnInvalidDataStrategy.java
examples/systemout/test_dir.sh
pom.xml

Adds a simple example that dumps to `System.out`.
Resolves #175 
Adds a parent (aggregator) POM, and one example.
I ran it on some test files. Satisfactory results were reported in the comments for #175.

examples: add System.out example code

---

api/src/main/java/org/jmisb/api/klv/RawMisbMessage.java

Fixes one compiler warning:
```
[INFO] /home/bradh/jmisb/api/src/main/java/org/jmisb/api/klv/RawMisbMessage.java: /home/bradh/jmisb/api/src/main/java/org/jmisb/api/klv/RawMisbMessage.java uses unchecked or unsafe operations.
[INFO] /home/bradh/jmisb/api/src/main/java/org/jmisb/api/klv/RawMisbMessage.java: Recompile with -Xlint:unchecked for details.
```
Changes call to return a typed Set.

api: fix unchecked warning

---

README.md
examples/README.md
examples/movingfeatures/README.md
examples/movingfeatures/pom.xml
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/Coordinate.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/CoordinateSerialiser.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/Main.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/MovingFeaturesCollection.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/MovingFeaturesCollectionSerialiser.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/MovingFeaturesConverter.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/MovingPoint.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/MovingPointSerialiser.java
examples/pom.xml

This is some example code that shows how to collect VMTI results and merge them to a different data model.
The OGC has an activity that looks like this in TB16.
Adds example code, include some documentation.
Ran it on a couple of test files, checked the output against the JSON schema for mf-json, and viewed it in mf-cesium.
Seems OK for now.

examples: add example of VMTI to OGC Moving Features

---

pom.xml

Upgrades the ffmpeg-platform dependency to the current version (FFmpeg 4.3.1).
This just keeps us on the latest released version, likely quite a lot of bug fixes that we might or might not hit anyway. It isn't providing any additional functionality at this stage.
No code changes. Just upgrades the dependency.
Full build / unit tests.
Ran viewer application on some example files.
Ran generator example, looked at output in systemout example.
No issues noted.

upgrade to FFmpeg 4.3.1

---

viewer/README.md
viewer/pom.xml
viewer/src/main/java/org/jmisb/viewer/MisbViewer.java
viewer/src/main/java/org/jmisb/viewer/map/MapFrame.java
viewer/src/main/java/org/jmisb/viewer/map/SensorFootprintPainter.java
viewer/src/main/java/org/jmisb/viewer/map/SensorLocationPainter.java
viewer/src/main/resources/configuration.properties

Adds a map view to the viewer. Update to #259.
Uses the LGPL licensed JXMapViewer2 component, along with some custom rendering.
Tested with the viewer application on some realistic data (WASABI from MISB, and the ESRI examples). Seems fine.

feat: initial version of map view

---

examples/README.md
examples/mimdgenerator/README.md

The MIMD generator example was added as part of #260, but I didn't include appropriate documentation. This PR addresses 
the missing documentation.
Adds an README.md file for the MIMD generator example, and links that into the main examples/README.md file.
I re-ordered the examples to make them match typical display order in the IDE or file browser (i.e. alphabetical).
No testing. I did check it with vscode and the markdownlint extension.
N/A.
- [N/A] I have added tests to cover my changes.

docs: update examples docs for mimdgenerator

---

devsupport/st1201/st1201.py

Some minor code cleanups based on LGTM static analysis.
We might want to add that to the project. Will raise a ticket if desired.
Fixes a broken comparison, and removed an unused import.
No changes on the Java side - neither production nor test code.
Re-ran the test case generator, and compared the results to existing (api/src/test/resources/org/jmisb/api/klv/st1201/st1201tests.json) tests. No changes.
N/A

fix: clean up st1201 devsupport code

---

api/src/main/java/org/jmisb/api/klv/st0601/WaypointList.java

Avoid using Boolean in ST0601 WaypointList.
This is another issue flagged by LGTM, but I waited to action it to avoid potential merge conflicts (with #274).
Simple replacement with `boolean`.
Unit tests only (as part of a full build). I don't have any real data that uses this tag.
N/A.

fix(st0601): avoid unneeded boxing of boolean

---

.github/workflows/jdk11.yml
api/pom.xml
core/pom.xml
miml-maven-plugin/pom.xml
pom.xml

Related to the CI failures (which I can occasionally repeat locally, nothing like as frequently as GH actions), I've started investigation. To help, this adds a new profile  - `debug` that turns up the javacpp debug as well as surefire and failsafe debugging.
No code changes, but changes build output if you enable the debug profile. That profile is enabled on the jdk11 build.
Local builds with and without the profile.
Also some test builds on my jmisb fork.

task: add debug profile to help debug testing

---

examples/mimdgenerator/src/main/java/org/jmisb/examples/mimdgenerator/Generator.java
miml-maven-plugin/src/main/java/org/jmisb/maven/ClassModelEntry.java
miml-maven-plugin/src/main/resources/templates/realClassTest.ftl
viewer/src/main/java/org/jmisb/viewer/map/MapFrame.java

Minor update to the MIMD generator, but also includes a fix to the MIMD base code
where I noted a lack of accuracy in display - three decimal places just isn't enough for
a location (lat/lon) expressed in radians.
Updates MIMD base code and generator example.
Updated unit tests, full rebuild.
Generated out file, and ran it in the viewer application.

examples(mimd): extend MIMD generator example with footprint info

---

api/src/test/java/org/jmisb/api/klv/st1108/st1108_3/metric/MetricLocalSetsKeysTest.java

During work on #298 I noted a badly named test in my recent ST 1108 work.
Rename test class. No functional changes.
Just did a full build with all unit tests

st1108: rename test

---

.travis.yml

Travis CI is no longer doing anything. 
Remove unused configuration file.
Only as part of the PR.

ci: remove unused travis configuration

---

api/src/test/java/org/jmisb/api/klv/st0601/NestedSARMILocalSetTest.java

This is a low-priority PR to add some missing test coverage for one class in the ST 0601 implementation
Add unit tests for `NestedSARMILocalSet`.
Full build to run unit tests. Verified coverage using jacoco report.

st0601: add unit tests for NestedSARMILocalSet

---

api/src/main/java/org/jmisb/api/klv/st1201/DecodeResult.java
api/src/main/java/org/jmisb/api/klv/st1201/FpEncoder.java
api/src/main/java/org/jmisb/api/klv/st1201/ValueMappingKind.java

There is a draft ST 1201.5, which I'm implementing to check it out.
During that, I found a few issues with documentation (and one warning) that are worth fixing even if ST 1201.5 never makes it.
Also fixing those issues here makes the changes for .5 better isolated.
Fix javadocs, and make one method final.
Full rebuild.

st1201: editorial cleanups

---

pom.xml

No specific need for this version, just keeping up with current.
Upgrades version of an existing dependency to be current.
There are no code change or effects on outputs.
Full build with the `dependencycheck` profile enabled.

dependency-check: bump version to 6.5.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/jdk11.yml
.github/workflows/jdk14.yml
.github/workflows/macos.yml
.github/workflows/qa.yml
.github/workflows/windows.yml

Adds GH test coverage for work on the 2.x branch
Modify existing test matrix with additional branch.
N/A. Testing as part of the PR.

ci: Add 2.x branch to provide test coverage

---

api-ffmpeg/src/main/java/org/jmisb/api/video/CodecConfiguration.java
api-ffmpeg/src/main/java/org/jmisb/api/video/CodecConfigurations.java
api/src/main/java/org/jmisb/api/klv/st0102/SecurityMetadataKey.java
api/src/main/java/org/jmisb/api/klv/st0102/universalset/SecurityMetadataUniversalSet.java
api/src/main/java/org/jmisb/api/klv/st0601/ActivePayloads.java
api/src/main/java/org/jmisb/api/klv/st0601/ActiveWavelengthList.java
api/src/main/java/org/jmisb/api/klv/st0601/ControlCommandVerification.java
api/src/main/java/org/jmisb/api/klv/st0601/PayloadList.java
api/src/main/java/org/jmisb/api/klv/st0806/RvtLocalSet.java
api/src/main/java/org/jmisb/api/klv/st0806/RvtMetadataIdentifier.java
api/src/main/java/org/jmisb/api/klv/st0903/VTargetSeries.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/AbstractTargetLocationOffset.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/BoundaryBottomRightLatOffset.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/BoundaryBottomRightLonOffset.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/BoundaryTopLeftLatOffset.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/BoundaryTopLeftLonOffset.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/TargetBoundarySeries.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/TargetHAE.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/TargetLocation.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/TargetLocationOffsetLat.java
api/src/main/java/org/jmisb/api/klv/st0903/vtarget/TargetLocationOffsetLon.java
api/src/main/java/org/jmisb/api/klv/st0903/vtrack/VTrackItemSeries.java
api/src/main/java/org/jmisb/api/klv/st0903/vtracker/BoundarySeries.java
api/src/main/java/org/jmisb/api/klv/st0903/vtracker/TrackHistorySeries.java
api/src/main/java/org/jmisb/api/klv/st1403/SARMIValidator.java
api/src/main/java/org/jmisb/api/klv/st1403/ValidationResults.java
examples/movingfeatures/src/main/java/org/jmisb/examples/movingfeatures/MovingPointSerialiser.java
pom.xml

It looks like the activation was dropped when consolidating the plugin, so the formatter isn't running on build.
Re-enable code formatter (top level pom.xml change).
Commit reformatted code.
Full build.

2.x: enable formatting and update for results

---

elevation/geoid/src/main/java/module-info.java
examples/movingfeatures/src/main/java/module-info.java

Looks like I missed a couple of bits when the reformat plugin got enabled. This PR updates it.
Trivial reformatting.
Build test only.

2.x: minor formatting fixes for module-info entries

---

pom.xml

There are known issues with log4j 2.14.1 and earlier. I don't think we're vulnerable in the same way, but probably worth updating. This is the 2.x branch update.
Just updates to the latest 2.15.0 version of log4j. No code changes.
Just ran unit tests, and verified viewer application and systemout example is OK.

update log4j dependency to 2.15.0

---

pom.xml

There are known issues with log4j 2.14.1 and earlier. I don't think we're vulnerable in the same way, but probably worth updating. This is the develop branch update.
Just updates to the latest 2.15.0 version of log4j. No code changes.
Just ran unit tests, and verified viewer application and systemout example is OK.

update log4j to 2.15.0

---

pom.xml

log4j2 has been upgraded again (2.16.0). We don't need this for the recent CVE, but it does provide additional hardening.
See https://lists.apache.org/list.html?log4j-user@logging.apache.org
Bump in managed dependencies.
Full build, ran viewer. No issues noted.

deps: upgrade log4j (again) - 2.x

---

pom.xml

Minor version bump on commons-cli. This is only used in the examples.
Update in centrally managed dependency.
Full build, light testing only of systemout example. No problems noted.

deps: update commons-cli to 1.5.0 (2.x)

---

README.md

As for #341, this is the develop branch version.
As for #341.
N/A.

doc: update MISB home page link

---

pom.xml

We've recently upgraded log4j on the 2.x branch (#343 for 2.15.0 and #346 for 2.16.0) as well as on develop branch (#344 for 2.15.0). However there is another issue which has resulted in log4j2 2.17.0. As before, doesn't look like we'd be vulnerable, but these are high profile issues and easy upgrades, so should be incorporated.
This is the 2.x branch version.
Upgraded log4j in managed dependencies. No code changes.
Full build including unit tests
Ran viewer application with a file that I know generates log messages ("Day Flight.mpg), verified it is still OK.

deps: upgrade log4j2 to 2.17.0 (2.x)

---

pom.xml

Minor version bump for the antlr dependency. Nothing critical in that, just keeping up.
Resolve #347 
Update version in managed deps. No code changes
Full rebuild. Since we only use that for the MIML maven plugin, I think that is sufficient.

deps: bump antlr-runtime dependency to 4.9.3

---

pom.xml

General upgrade to maven dependencies.
Resolves #348.
It looks like we can use a single version number to bump core and plugin along with the "main" maven version.
Just a full build, which I think is reasonable given we really only need this for MIML plugin.

deps: upgrade maven dependencies

---

pom.xml

Minor version upgrade to Checkstyle. See https://checkstyle.sourceforge.io/releasenotes.html for changes - nothing critical, but keeping up.
Resolves #350
Upgrades version only, no code changes.
Full build only. Since this is a compile-time check, that seems sufficient.

deps: upgrade Checkstyle to 9.2 (2.x)

---

pom.xml

Minor version upgrade to JQF dependencies.
Resolves #359.
Version bump only. No code changes.
Full build, and ran fuzzer script.

deps: upgrade jqf (fuzzer) dependencies (2.x)

---

pom.xml
viewer/src/main/java/org/jmisb/viewer/map/MapFrame.java

Upgrades the spotbugs support we have to be current.
Resolves #349 
Bumps the versions of spotbugs and the associated maven plugin  in managed dependencies to latest.
This introduces a new check that showed a problem in the viewer application (with catching null pointer exceptions), which is addressed.
Full build (since that is where spotbugs applies).
Ran viewer application to check map is still working correctly - tried a couple of files, seems good.

deps: upgrade spotbugs to 4.5.2  (2.x)

---

pom.xml

There is another upgrade for log4j2 - this time its 2.17.1. Again, do not think we're vulnerable, but we should upgrade.
Relates #368.
Upgrade in managed dependencies.
Full build, checked viewer application with a test file I know creates log messages.

deps: upgrade log4j2 to 2.17.1 (2.x)

---

pom.xml

There is another upgrade for log4j2 - this time its 2.17.1. Again, do not think we're vulnerable, but we should upgrade.
Resolves #368.
Upgrade log4j2 version in pom.xml.
Full build only.

deps: upgrade log4j2 to 2.17.1 (develop branch)

---

pom.xml

Minor version bump for checkstyle plugin to 9.2.1 (was 9.2). Not critical, just keeping up.
Upgrade in properties in central pom.
Full build only. I think that is OK, given that is when checkstyle applies.

deps: checkstyle 9.2.1

---

pom.xml

This is a minor version upgrade for the spotbugs plugin.
The changes are pretty minor - see https://github.com/spotbugs/spotbugs/releases/tag/4.5.3
There is a log4j2 related dependency bump in there (which doesn't look like a vulnerability to me, since we're running it on trusted code, but given the environment of the day, is understandable to mention).
Upgrade property value from 4.5.2 to 4.5.3 in managed dependencies.
Full build. No errors noted.

deps: upgrade spotbugs to 4.5.3

---

pom.xml

Version bump on an important test dependency. A list of changes is provided at https://github.com/cbeust/testng/milestone/5?closed=1 (possibly not everything). I don't see anything critical for us, but worth upgrading.
Version upgrade in managed dependencies.
Full build. Since this is only a test dependency, that is sufficient.

deps: upgrade testng to 7.5

---

pom.xml

This is  a low priority upgrade to checkstyle 9.3. Currently we have 9.2.1. 
The changes in 9.3 are shown at https://checkstyle.org/releasenotes.html#Release_9.3
I don't think there is anything in there we particularly need. This is just to keep current, and position for future JDK 17 support.
Update the version in managed dependencies.
Just did a full build. This tool is only compile-time, so that seems appropriate.

deps: bump checkstyle to 9.3

---

devsupport/fuzz.sh
pom.xml

Low priority upgrade of the JQF fuzzer and associated maven plugin to 1.9.
The changes from 1.8 (which we currently have) to 1.9 are shown in https://github.com/rohanpadhye/JQF/compare/jqf-1.8...jqf-1.9 - I couldn't find a set of release notes, but the changes look pretty minor. Nothing we really need, just keeping up.
Update the version in managed dependencies. Also a small tab -> space fix in the fuzz.sh script that I noted during testing.
Ran the fuzzer script for 1m (in lieu of 10m).

deps: update JQF fuzzer to 1.9

---

pom.xml

log4j2 2.17.2 is a bug-fix release. The changes are listed at https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.2
Nothing in that seems particularly important for our usage, but given the recent work, seems useful to stay up-to-date.
Modify the version in managed dependencies.
Full build / unit tests only.
N/A.

deps: bump log4j2 to 2.17.2

---

pom.xml

Minor updates to some dependencies. Nothing in there that is particularly important, just keeping up.
Update checkstyle (9.3 to 10.0), guava (31.0.1 to 31.1), jackson (2.13.1 to 2.13.2), maven (3.8.4 to 3.8.5) and spotbugs (4.5.3 to 4.6.0).
Just a full build. These are all just compile-time dependencies, so that seems appropriate.

2.x: update dependencies

---

examples/generator/pom.xml
pom.xml

Minor version upgrades. There is nothing particularly critical in this, although the jackson one looks important, and log4j2 is still topical.
There are other upgrades that we could do (in particular ffmpeg presets) but I don't want to couple that into this minor update.
Bump versions. No code changes.
Full build.
Ran viewer application - no problems noted.
Checked generator example.

deps: upgrade jackson, testng, log4j2, commons-cli

---

api-ffmpeg/pom.xml
api-ffmpeg/src/test/java/org/jmisb/api/video/FrameConverterTest.java
api-ffmpeg/src/test/java/org/jmisb/api/video/LoggerChecks.java
api-ffmpeg/src/test/java/org/jmisb/api/video/VideoFileInputTest.java
api-ffmpeg/src/test/java/org/jmisb/api/video/VideoStreamInputTest.java
api/src/main/java/org/jmisb/api/klv/st1204/CoreIdentifier.java
api/src/test/java/org/jmisb/api/klv/st1204/CoreIdentifierTest.java
api/src/test/java/org/jmisb/api/klv/st1204/CoreIdentifierTortureTest.java
devsupport/check_loggers/README.md
devsupport/check_loggers/check_loggers.py
st0102/src/main/java/org/jmisb/st0102/ObjectCountryCodeString.java
st0102/src/test/java/org/jmisb/st0102/universalset/SecurityMetadataUniversalSetTest.java
st0102/src/test/java/org/jmisb/st0102/universalset/UniversalSetFactoryTest.java
st0601/src/test/java/org/jmisb/st0903/vtrack/VTrackItemTest.java
st0602/src/main/java/org/jmisb/st0602/AnnotationMetadataUniversalSet.java
st0602/src/test/java/org/jmisb/st0602/AnnotationMetadataUniversalSetTest.java
st1108/src/test/java/org/jmisb/st1108/InterpretabilityQualityLocalSetFactoryTest.java

I added a check script for logging issues a while back, but its since bit-rotted (as noted in #280).
This PR fixes the script, and also some of the issues that it identified.
Resolves #280.
Rework the script to match the new 2.x structure, fix bugs in the scripting, and make it run from the top level checkout.
Adds documentation on what is supposed to happen.
There are some fixes to add missing checks in tests, and also to correct a couple of typos in the logging that those checks showed up.
Ran the script progressively, checked results against changes as I worked through the issues reported.
Did a full build, all unit tests.

fix logger check test script

---

pom.xml

General upgrade of dependencies on 2.x branch. 
Minor or point release changes in managed dependencies.
Unit test build only. These are mostly compile-time dependencies.

chore: upgrade dependencies

---

miml-maven-plugin/pom.xml

During a recent PR, I saw an unrelated QA failure related to MIML for an out-of-date dependency (indirectly used).
There is a CVE against that dependency, and while it doesn't appear to be exploitable in our use, I think it is important to fix.
Updates the dependency in the maven-miml-plugin. 
Just a build check. Since the plugin is used only for build, that seems OK.

miml: update maven-core dependency

---

pom.xml

Minor version upgrades for some of the build-time dependencies: maven, plexus-utils and testng.
Just bumps versions in the managed deps.
Full build, including dependencycheck profile. That seems appropriate given that these deps are all linked to build.
Subsequently also used the viewer test app (from upgraded versions) to check some new files. Seems fine - no issues noted.

2.x: upgrade dependency versions

---

pom.xml

This is a minor version upgrade for log4j2 (from 2.17.2 to 2.18.0) for the 2.x branch.
The changes are listed at https://logging.apache.org/log4j/2.x/changes-report.html#a2.18.0 - nothing we particularly need, but useful to keep up with current.
Upgrades version in managed dependencies.
Full build.
Tested viewer app with file that produces log output.
N/A.

deps: upgrade log4j to 2.18.0 (2.x)

---

pom.xml

Minor bug fix release. See https://github.com/cbeust/testng/releases/tag/7.6.1 for changes.
Updates version in managed deps.
Full build.

deps: update testng from 7.6.0 to 7.6.1

---

pom.xml

Micro version bump for spotbugs.
Changes at https://github.com/spotbugs/spotbugs/releases/tag/4.7.1 - nothing that looks important, just keeping up.
Bump version in managed deps.
Full build with unit tests.

deps: bump spotbugs from 4.7.0 to 4.7.1

---

pom.xml

Bump checkstyle from 10.3 to 10.3.2.
See https://checkstyle.org/releasenotes.html#Release_10.3.2  (for 10.3.1 and 10.3.2).
Update version in managed dependencies.
Full build and unit tests.

deps: bump checkstyle to 10.3.2

---

README.md

#420 identified that we might need a bit more context for getter and setter methods.
Add extra details to README.md.
N/A

doc: additional README context

---

pom.xml

Minor version update in ANTLR 4. 
Changes from 4.10.1 to 4.11.1 are at https://github.com/antlr/antlr4/releases (its really 4.10.1 to 4.11.0, there are no changes in 4.11.0 to 4.11.1, except for the naming of the artifact). Nothing we need, but there is mention of a security issue, and its worth keeping up.
Upgrade version in managed dependencies.
Just a full build and unit tests. This is a build-time tool, so should be sufficient.

chore: bump ANTLR to 4.11.1

---

pom.xml

Updates spotbugs from 4.7.1 to 4.7.2. Changes are identified at https://github.com/spotbugs/spotbugs/releases/tag/4.7.2 - nothing we need, just keeping current.
I had hoped for a fix for https://github.com/spotbugs/spotbugs/issues/2126 but that was resolved after 4.7.2 was released, so its probably 4.7.3.
Bump version in managed dependencies. No code changes.
Unit tests only. That seems appropriate given its a build-time check.

chore: bump spotbugs to 4.7.2

---

api-awt/pom.xml
core/pom.xml
elevation/geoid/pom.xml
miml-maven-plugin/pom.xml
pom.xml
st0805/pom.xml
st1403/pom.xml
st1909/pom.xml

#421 bumped to slf4j 2.0.1. About that time, they released 2.0.2. The changes are minor (currently up at https://www.slf4j.org/news.html) and don't affect us, but this helps us keep up.
While checking this, I noted a few places in the build where there were warnings about not having an implementation. Added a test logger to silence that.
Updates version in managed dependencies, and adds dependency on test logger.
Unit tests, and verified that viewer application produces log messages on known-noisy data.

chore: bump slf4j to 2.0.2

---

pom.xml

Checkstyle has a micro version upgrade (10.3.3 to 10.3.4). Changes are https://checkstyle.sourceforge.io/releasenotes.html#Release_10.3.4 and nothing I see of concern. This is just routine maintenance.
Update to managed dependency.
Just full build test. This is a compile-time tool, so that should be sufficient.

chore: bump checkstyle to 10.3.4

---

dependency-check-suppression.xml
pom.xml

This updates the 2.x branch to current versions of build tools and compile dependencies.
Updates managed dependency versions in top level POM.
Full build (which covers off maven, spotbugs, the maven shade tool, checkstyle, most of jackson databind).
Ran viewer application, checked video and metadata display on various files, checked log outputs on files with known issues (covers off slf4j, ffmpeg, jackson).
Ran viewer on existing ST 0602 SVG file (from annotation example), checked output (covers off more ffmpeg and svgSalamander).
- [N/A ] I have added tests to cover my changes.

deps: multiple dependency upgrades

---

pom.xml

There is a CVE against testng 7.6.1 (that may or may not be a real security issue). 7.7.0 just got released.
Upgrade version in managed dependencies. No code changes.
Full build including unit tests and integration tests.
- [N/A] I have added tests to cover my changes.

deps: bump testng to 7.7.0

---

pom.xml

Micro version bump of testng dependency.
Changes are at https://github.com/cbeust/testng/releases/tag/7.7.1. Nothing we need, maintenance only.
Update version in managed dependencies.
Full build with unit tests only.

deps: bump testng to 7.7.1

---

pom.xml

Updates to build-time dependencies. Nothing we need, but keeping current.
These are all minor or micro-version changes.
Update version in managed properties. No code changes.
Full build only. The changes are either test-only changes, or are used by the maven plugin for MIMD.

deps: bump freemarker, checkstyle, maven and slf4j test
