WestRidgeSystems/jmisb

viewer/src/main/java/org/jmisb/viewer/MetadataPanel.java, viewer/src/main/java/org/jmisb/viewer/MisbViewer.java
This avoids confusion when the previous file did have metadata, but the new
file doesn't have (valid) metadata, so you see the old metadata with the new
video stream.
Modifies viewer to clear metadata.
Manual testing:
- load file with metadata
- load file without metadata
- check metadata pane does not have old data
- load file with metadata, ensure it shows up OK.
=> Clear metadata panel on load.

pom.xml
Works with javadoc from java 11, which is the default in some installs.
Compile test.
=> Upgrade javadoc

api/src/main/java/org/jmisb/api/klv/st0601/AirfieldBarometricPressure.java, api/src/main/java/org/jmisb/api/klv/st0601/DifferentialPressure.java, api/src/main/java/org/jmisb/api/klv/st0601/StaticPressure.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0601/UasPressureMillibars.java, api/src/main/java/org/jmisb/api/klv/st0601/WindDirectionAngle.java, api/src/main/java/org/jmisb/api/klv/st0601/WindSpeed.java, api/src/test/java/org/jmisb/api/klv/st0601/AirfieldBarometricPressureTest.java, api/src/test/java/org/jmisb/api/klv/st0601/DifferentialPressureTest.java, api/src/test/java/org/jmisb/api/klv/st0601/StaticPressureTest.java, api/src/test/java/org/jmisb/api/klv/st0601/WindDirectionAngleTest.java, api/src/test/java/org/jmisb/api/klv/st0601/WindSpeedTest.java, api/testng.xml
There are a few ST0601 tags that are only supported as opaque values. They show up as N/A in the viewer.
Implement support for Tag 35 and 36 (wind), and 37/49/53 (pressure variations).
Added unit tests, ran with one of the MISB samples that has those tags (HD_H264_0903_TS_SYN_V1_001.mpg  - requires ignoring checksums).
=> Add ST0601 types for pressure and wind speed / direction.

api/src/main/java/org/jmisb/api/klv/st0601/PlatformRollAngle.java, api/src/test/java/org/jmisb/api/klv/st0601/PlatformRollAngleTest.java
Implementation borrowed from PlatformPitchAngle.
Platform Roll Angle (Tag 7) has a special case for "out of range": `0x80 0x00`. That is partly implemented.
Completes the implementation based on the PlatformPitchAngle impl.
Added new unit test.
=> Complete handling for ST0601 PlatformRollAngle special case.

api/src/test/java/org/jmisb/api/klv/st0601/CornerOffsetTest.java
The LongitudePoint4 is just below this, its a typo fix.
This is a minor fix for test coverage. It has no functional impact.
Ran unit tests, inspected test coverage.
=> Fix typo on OffsetCornerLongitudePoint3 factory method test.

api/src/main/java/org/jmisb/api/klv/st0601/PlatformGroundSpeed.java, api/src/main/java/org/jmisb/api/klv/st0601/PlatformIndicatedAirspeed.java, api/src/main/java/org/jmisb/api/klv/st0601/PlatformTrueAirspeed.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkSpeed.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/PlatformGroundSpeedTest.java, api/src/test/java/org/jmisb/api/klv/st0601/PlatformIndicatedAirspeedTest.java, api/src/test/java/org/jmisb/api/klv/st0601/PlatformTrueAirspeedTest.java
This implements support for Tag 8, 9 and 56. They are basically the same, although the semantics are different.
This is a very simple tag mapping, implemented in shared code.
Added unit tests, checked coverage changes.
Also ran this in the viewer application against some of the MISB test data (e.g. HD_MP2_06011_TS_ASYN_V1_001.mpg) which uses these tags.
=> Add support for Platform True Airspeed, Indicated Airspeed and Ground Speed

api/src/test/java/org/jmisb/api/klv/st1201/FpEncoderTest.java, api/src/test/java/org/jmisb/api/klv/st1201/ST1201AnnexATest.java
Minot test improvements for ST1201 (FpEncoder). No functional changes.
This moves the test to match the implementing class, and adds one more test from Annex A to ST1201.
Added new unit test, ran existing tests.
=> Minor test tweaks for ST1201 (IMAPB)

api/pom.xml, api/src/main/java/org/jmisb/api/klv/st0102/SecurityMetadataMessage.java, api/src/main/java/org/jmisb/api/klv/st0102/localset/SecurityMetadataLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkMessage.java, api/src/test/java/org/jmisb/api/klv/KlvParserTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/UnknownTagTest.java
Resolves #17
The change is basically to replace the `throw` with logging, and tests that verify it works.
I did consider the suggestion in #17 to add as an `OpaqueValue` but that will require much larger changes, because it stretches the API contract about tags being known values. The MISB standards say to drop, so that seems reasonable.
Unit testing.
(This is arguably a breaking change in that jmisb works differently in the presence of unknown tags, but since it only ignores single fields, I think that is reasonable to consider this a bug fix)
=> Avoid throwing on unknown tags.

api/src/main/java/org/jmisb/api/klv/st0601/TargetTrackGateHeight.java, api/src/main/java/org/jmisb/api/klv/st0601/TargetTrackGateSize.java, api/src/main/java/org/jmisb/api/klv/st0601/TargetTrackGateWidth.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/TargetTrackGateSizeTest.java
Add support for unhandled Target Track Gate Width (Tag 43) and Target Track Gate Height (Tag 44).
Shared implementation, updates to factory, and unit tests.
=> Add support for Target Track Gate Width and Height

api/src/main/java/org/jmisb/api/klv/st0601/GroundRange.java, api/src/main/java/org/jmisb/api/klv/st0601/SlantRange.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0601/UasRange.java, api/src/test/java/org/jmisb/api/klv/st0601/GroundRangeTest.java, api/src/test/java/org/jmisb/api/klv/st0601/SlantRangeTest.java
Implements an unsupported tag (57).
This is essentially the same type as Slant Range. Refactored to a shared superclass.
Also corrected test for Slant Range - it just needed more precision.
=> Add support for Ground Range tag

api/src/main/java/org/jmisb/api/klv/st0601/TargetErrorEstimateCe90.java, api/src/main/java/org/jmisb/api/klv/st0601/TargetErrorEstimateLe90.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTargetErrorEstimate.java, api/src/test/java/org/jmisb/api/klv/st0601/TargetErrorEstimateCe90Test.java, api/src/test/java/org/jmisb/api/klv/st0601/TargetErrorEstimateLe90Test.java
Implements missing KLV tags for target error estimates.
Implementation uses shared superclass - the semantics between these values are quite different, although the value mapping is the same.
Includes changes to factory method and unit tests.
Unit tests.
Used viewer application on one of the MISB First Level Integration tests to check display.
=> Implement LE90 and CE90 target error estimate (Tag 45/46)

api/src/main/java/org/jmisb/api/klv/st0601/AirfieldElevation.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/UasDatalinkAltitudeTest.java
Adds support for a missing ST0601 tag.
This is really just another example of UasDatalinkAltitude, so just implements that superclass, and adds corresponding tests and factory method implementation.
Unit tests, plus the viewer application on MISB test data that uses this tag.
=> Add support for Airfield Elevation (Tag 54).

api/src/main/java/org/jmisb/api/klv/st0601/TargetTrackGateSize.java
We had a comment about 2px vs 1px in the Target Track Gate Size implementation. That is fixed in ST0601.16 and the comment is no longer valid.
Updated API docs.
N/A.
=> Fix comment about resolution for Target Track Gate Height / Width

api/src/main/java/org/jmisb/api/klv/st0601/OnBoardMiStorageCapacity.java, api/src/test/java/org/jmisb/api/klv/st0601/OnBoardMiStorageCapacityTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
The subject tag is variable length (1-4 bytes). This extends the implementation and tests to handle the three byte case.
Resolves #75.
The output is still 1, 2 or 4 bytes. This just makes input more flexible.
Updates `PrimitiveConverter` implementation to support that, and extends the test coverage
for `PrimitiveConverter`. That implementation is currently only used for the subject tag, although I'm about to implement other tags that require it (e.g. ~~Leap Seconds~~, Time Airborne, Propulsion Unit Speed).
N/A
=> Update Onboard MI Storage Capacity to support three byte input.

api/src/test/java/org/jmisb/api/klv/st0601/MiisCoreIdentifierTest.java
This should have been in #65, but clearly wasn't. It shows up as a test coverage omission in UasDatalinkFactory.
No code changes, just improves test coverage. I did refactor the other tests a bit to avoid duplicate the byte array and strings.
N/A
=> Add test for factory method for MIIS Core Identifier.

api/pom.xml, core/pom.xml, pom.xml, viewer/pom.xml
Automates checking of potentially vulnerable dependencies.
This slows down the build, so not enabled by default. You need to use `-Pdependencycheck` to enable the profile.
It will also break the build until #81 is fixed. After that we could add an extra travis or github actions task.
Ran with and without the profile flag.
(sort-of developer feature?)
=> Add a maven profile to run dependency checks.

api/src/main/java/org/jmisb/api/klv/st0601/PropulsionUnitSpeed.java, api/src/main/java/org/jmisb/api/klv/st0601/TimeAirborne.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/PropulsionUnitSpeedTest.java, api/src/test/java/org/jmisb/api/klv/st0601/TimeAirborneTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
Adds support for two tags we previously didn't support.
These follow a fairly standard implementation of IUasDatalinkValue.
PrimitiveConverter is extended to provide shared implementation.
Includes applicable javadoc and full test coverage.
=> Implement Time Airborne (ST0601 Tag 110) and Propulsion Unit Speed (Tag 111)

api/src/main/java/org/jmisb/api/klv/st0601/LeapSeconds.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/LeapSecondsTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
Adds support for a tag we didn't previously support.
Fairly standard IUasDatalinkValue impl. Shares some variable-length encoding / decoding in PrimitiveConverter.
=> Add support for Leap Seconds (ST0601 Tag 136).

api/src/main/java/org/jmisb/api/klv/st0601/AirbaseLocations.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0601/dto/Location.java, api/src/test/java/org/jmisb/api/klv/st0601/AirbaseLocationsTest.java, api/src/test/java/org/jmisb/api/klv/st0601/dto/LocationTest.java
Implements ST0601 Tag 130, which we don't currently support.
Mostly fairly standard IUasDatalinkValue implementation. There are a few special cases for unknown and takeoff == recovery locations which makes the code more complex and leads to a couple of static constructor methods.
I think I have them all, including unit tests for each combination.
There is one unrelated javadoc fix in the UasDatalinkTag enum, which I missed during the ST0903 incorporation.
=> Implement Airbase Locations for ST0601

api/src/test/java/org/jmisb/api/klv/st0601/WaypointListTest.java
This removes one `System.out.println` debugging entry from WaypointListTest.
Not sure how I managed to leave that behind.  Doesn't do anything, just adds to the noise during a build.
Just deleted it.
Reran build.
=> Remove debugging output from WaypointListTest

api/src/main/java/org/jmisb/api/klv/st0903/vmask/BitMaskSeries.java, api/src/main/java/org/jmisb/api/klv/st0903/vmask/PixelPolygon.java, api/src/main/java/org/jmisb/api/klv/st0903/vtarget/AbstractPixelIndex.java, api/src/main/java/org/jmisb/api/klv/st0903/vtarget/PixelNumber.java, api/src/test/java/org/jmisb/api/klv/st0601/PropulsionUnitSpeedTest.java, api/src/test/java/org/jmisb/api/klv/st0601/TimeAirborneTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
During ST0903 work, there were a couple of byte conversions that seemed like they should be shared code, but I was worried about merge conflicts, so I duplicated the code and added TODO items. This  change pays down that technical debt.
Moves code around, adds tests.
There are two changes in tests for ST0601 classes where my earlier implementation only did 1, 2 and 4 bytes. The PrimitiveConverter will now do 3 bytes as well, so the tests needed update.
=> Move some duplicated code to PrimitiveConverter

api/src/main/java/org/jmisb/api/klv/st0903/vtracker/VTrackerLS.java
Just a minor comment cleanup - I was reviewing the TODO items, and this one showed up.
Just removes out-of-date comment.
Ran build / unit tests.
=> Remove out-of-date comment from VTrackerLS factory

api/src/main/java/org/jmisb/api/klv/st0601/SensorFrameRate.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/SensorFrameRateTest.java
Implements support for a tag we don't current parse.
Fairly standard IUasDatalinkValue implementation. There are really two cases - denominator == 1, and != 1. Parsing and generation are slightly different in those cases.
=> Implement ST0601 SensorFrameRatePack (Tag 127)

api/src/main/java/org/jmisb/api/klv/st0102/ObjectCountryCodeString.java, api/src/main/java/org/jmisb/api/klv/st0102/localset/LocalSetFactory.java, api/src/main/java/org/jmisb/api/klv/st0102/universalset/UniversalSetFactory.java, api/src/test/java/org/jmisb/api/klv/st0102/ObjectCountryCodeStringTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/LocallSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/OcMethodTest.java
Updates the Object Country Code encoding to be UTF-16. I assume this is some legacy thing, but that is what ST0102 requires (via RFC2781).
Resolves #100
Modifies the KLV ST0102 code to use a new UTF-16 string class (ObjectCountryCodeString).
Adds tests to match.
Unit testing.
=> Fix Object Country Code encoding

api/src/main/java/org/jmisb/api/klv/st0601/ControlCommand.java, api/src/main/java/org/jmisb/api/klv/st0601/ControlCommandVerification.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0601/WavelengthsList.java, api/src/test/java/org/jmisb/api/klv/st0601/ControlCommandTest.java, api/src/test/java/org/jmisb/api/klv/st0601/ControlCommandVerificationTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
Implements ST0601 Tag 115 and Tag 116, which we didn't previously support.
Fairly standard IUasDatalinkValue implementation. Minor extension to the PrimitiveConverter to handle byte[] -> long at an offset into the byte array, and extra tests for that.
N/A.
=> Implement ST0601 Control Command and Control Command Verification

api/src/main/java/org/jmisb/api/klv/st1201/FpEncoder.java, api/src/test/java/org/jmisb/api/klv/st1201/FpEncoderTest.java
While looking at the spotbugs reports (for a missing `default` in case statement), I tried to add a test for FpEncoder for 1 byte, which failed.
This corrects the code and adds the test. This is a bit separate from the spotbugs work, so providing it in advance.
It turns out `putChar()` actually writes two bytes - see https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#putChar-char-
This (unexpected to me) event causes a buffer overflow since we only allocate 1 byte. Instead, use plain `put()` which takes a single byte.
Unit test added.
N/A.
=> Fix encoding for 1 byte FpEncoder (ST1201).

api/src/main/java/org/jmisb/api/klv/st0601/PrecisionTimeStamp.java, api/src/main/java/org/jmisb/api/klv/st0603/ST0603TimeStamp.java, api/src/main/java/org/jmisb/api/klv/st0603/TimeStatus.java, api/src/main/java/org/jmisb/api/klv/st0603/package-info.java, api/src/main/java/org/jmisb/api/klv/st0903/PrecisionTimeStamp.java, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/EndTime.java, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/StartTime.java, api/src/test/java/org/jmisb/api/klv/st0601/PrecisionTimeStampTest.java, api/src/test/java/org/jmisb/api/klv/st0603/ST0603TimeStampTest.java, api/src/test/java/org/jmisb/api/klv/st0603/TimeStatusTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/EndTimeTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/StartTimeTest.java
This is a start on refactoring of common time stamp (ST0603) code into a separate module.
Relates to #97, but doesn't complete it.
Pulls out the common code into a new module. This is pretty minimal at the moment, but does make more shared code.
Also added the "time status" byte from ST0603.5 section 7.4. We need this to drop into the ST0604 video timestamp (see #102). It also helped to get the test coverage up which made Coveralls happier after the migration to common code reduced the coverage numbers (same amount of tests, just less covered lines, so lower percentage?)
Unit tests, with good coverage.
Ran the viewer application across a couple of test files - no problems noted.
=> Initial work on extracting time support to st0603 module

api/src/main/java/org/jmisb/api/klv/st0102/CountryCodingMethodUtilities.java, api/src/main/java/org/jmisb/api/klv/st0102/localset/OcMethod.java, api/src/main/java/org/jmisb/api/klv/st0601/CountryCodes.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0102/CountryCodingMethodUtilitiesTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/OcMethodTest.java, api/src/test/java/org/jmisb/api/klv/st0601/CountryCodesTest.java
Implements a tag we don't yet support.
Implements IUasMetadataValue, although the handling is slightly complicated by this having a couple of truncation cases. In addition, the coding method is encoded per ST0102 Object Country Code, so I refactored the conversion logic that was in `org.jmisb.api.klv.st0102.localset.OcMethod` into a utilities class, to make is reusable. (I did consider making that part of the `CountryCodingMethod` enumeration, but that made confusion with the ST0102 Tag 2 conversion more likely, so went with a separate class). 
Adds tests for all of the new `CountryCodes` class, the new utililties class, plus some extra tests for `OcMethod`.
=> Implement ST0601 Country Codes (Tag 122)

api/src/main/java/org/jmisb/api/klv/BerEncoder.java, api/src/test/java/org/jmisb/api/klv/BerEncoderTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/SecurityMetadataLocalSetTest.java
Resolves #124. We were switching to three-byte form at 128, which is valid, but not the minimal length encoding for lengths (for example) in the range 128-255. 
Changes the switchover point to 256. Adds tests
Unit tests.
=> Use two-byte BER-long for up to 255 

api/src/main/java/org/jmisb/api/klv/st0102/ObjectCountryCodeString.java, api/src/main/java/org/jmisb/api/klv/st0601/PayloadList.java
We have a couple of unused Charsets imports. This is all that is left of an earlier cleanup PR.
Modifies one stray (unused) import from PayloadList, and removes a stray (unused) import from the st0102 object country code string.
=> Use StandardCharsets where possible

api/src/main/java/org/jmisb/api/klv/st0903/shared/VmtiEnumeration.java, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/DetectionStatus.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/DetectionStatusTest.java
Tries to make DetectionStatus a bit easier to use. 
Resolves #123 
Adds static values to DetectionStatus. Also extends the parent VmtiEnumeration class to have a better equals() behaviour.
The implementation requires a static initializer block to ensure that things get constructed in the right order - it will fail without this.
Unit tests.
N/A.
=> Add enum values to ST0903 DetectionStatus

api/src/main/java/org/jmisb/api/klv/st0601/CorrectionOffset.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/CorrectionOffsetTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
Adds support for an ST0601 Tag (137 - Correction Offset) that we don't currently support.
Fairly standard IUasDatalinkValue implementation. Adds some extra functionality to the PrimitiveConverter for signed 64 bit values with variable length representation - that is described in the Motion Imagery Handbook 2020.1, section 7.3.10 "Integer".
N/A.
=> Implement ST0601 Correction Offset

api/src/main/java/org/jmisb/api/klv/st1204/CoreIdentifier.java, api/src/test/java/org/jmisb/api/klv/st1204/CoreIdentifierTest.java, api/src/test/java/org/jmisb/api/klv/st1204/UUIDCombinationTest.java, core/src/main/java/org/jmisb/core/klv/UuidUtils.java, core/src/test/java/org/jmisb/core/klv/UuidUtilsTest.java
Adds the ST1204.3 UUID combination approach.
Resolves #84 
This PR replaces #86 which was too badly conflicted.
Implements new algorithm for UUID combination (e.g. for sensors in a LVMI scenario).
Also adds a bit more javadoc.
Unit tests to match to the example in ST1204.3 scenario.
=> Implement ST1204.3 UUID combination approach

api/src/main/java/org/jmisb/api/klv/st0601/PrecisionTimeStamp.java, api/src/main/java/org/jmisb/api/klv/st0601/TakeOffTime.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0603/ST0603TimeStamp.java, api/src/main/java/org/jmisb/api/klv/st0903/PrecisionTimeStamp.java, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/EndTime.java, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/StartTime.java, api/src/test/java/org/jmisb/api/klv/st0601/TakeOffTimeTest.java, api/src/test/java/org/jmisb/api/klv/st0603/ST0603TimeStampTest.java, api/src/test/java/org/jmisb/api/klv/st0903/PrecisionTimeStampTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/EndTimeTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/StartTimeTest.java, core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
Adds support for a tag we don't currently support.
IUasDatalinkValue implementation, with support via the ST0603 timestamp code we already had, extended to handle the "variable up to 8 bytes" encoding. 
That is also useful in ST0903 timestamps, which are now required to be 8 bytes, but previously supported variable length encoding (typically 7 bytes). 
There was a knock-effect to other users of the ST0603 code, but its mostly in the tests.
The variable-length encoding/decoding required extension to the PrimitiveConverter.
=> Implement ST0601 Take Off Time (Tag 131).

api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/main/java/org/jmisb/api/klv/st0601/WeaponFired.java, api/src/main/java/org/jmisb/api/klv/st0601/WeaponLoad.java, api/src/test/java/org/jmisb/api/klv/st0601/WeaponFiredTest.java, api/src/test/java/org/jmisb/api/klv/st0601/WeaponLoadTest.java
Adds support for a couple of tags we don't yet support. Tag 60 and 61 are very similar.
Fairly standard IUasDatalinkValue implementations - some minor differences because of unpacking nibbles from byte array, but nothing special.
Includes tests.
Unit tests, plus some of the MISB FLI data has examples of Weapon Load (its all zero, which isn't actually valid, but it still works).
=> Add support for ST0601 Tag 60 "Weapon Load" and Tag 61 "Weapon Fired"

api/src/main/java/org/jmisb/api/klv/st0601/EventStartTimeUtc.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/EventStartTimeUtcTest.java
Implements a tag we didn't previously support. This one occurs in a reasonable number of the test files I have.
IUasDatalinkValue implementation. It makes use of the ST0603 changes that I brought in as part of Take Off Time implementation.
Includes documentation and tests.
Unit tests, plus viewer application. Note that the ESRI samples don't set this correctly - its all 0x00 bytes. We tolerate that, and render that as the start of the epoch (1970).
N/A.
=> Implement ST0601 Event Start Time - UTC (tag 72)

core/src/main/java/org/jmisb/core/klv/PrimitiveConverter.java, core/src/test/java/org/jmisb/core/klv/PrimitiveConverterTest.java
Resolved #137 - see that for the background.
Modifies existing converters to `clone()` returned (mutable) buffers.
Unit tests in `core`, plus checked it works right in my ST0806 generation tests.
=> Allow reuse of buffers in conversion to byte arrays

api/src/main/java/org/jmisb/api/klv/st0601/MiisCoreIdentifier.java, api/src/main/java/org/jmisb/api/klv/st1204/CoreIdentifier.java, api/src/test/java/org/jmisb/api/klv/st0601/MiisCoreIdentifierTest.java, api/src/test/java/org/jmisb/api/klv/st1204/CoreIdentifierTortureTest.java
While testing some old Alticam data, I saw MIIS Core Identifiers that have inconsistent usage and lengths (e.g. bit flags that suggest window IDs, but not enough bytes to provide the window ID GUID). That causes parsing to fail.
Add length checks, and return null if it doesn't work out (which probably means its garbage). Also add null checks to users.
We already have protection on the framing code.
Re-ran unit tests. Tested against the problematic file.
=> Add protection for bad MIIS core idents

api/src/main/java/org/jmisb/api/klv/st0601/ST0601Version.java, api/src/test/java/org/jmisb/api/klv/st0601/ST0601VersionTest.java
Resolves #26.
Modifies the ST0601 LS Version (Tag 65) to be a short.
This is potentially an ABI break, but should be fine with a rebuild.
Ran unit tests. 
Also checked one of the MISB integration test examples in the viewer app.
=> st0601: switch version to be short.

api/src/main/java/org/jmisb/api/video/DemuxReturnValue.java, api/src/main/java/org/jmisb/api/video/DemuxerUtils.java, api/src/main/java/org/jmisb/api/video/FileDemuxer.java, api/src/main/java/org/jmisb/api/video/IFileEventListener.java, api/src/main/java/org/jmisb/api/video/IVideoFileInput.java, api/src/main/java/org/jmisb/api/video/MetadataDecodeThread.java, api/src/main/java/org/jmisb/api/video/StreamDemuxer.java, api/src/main/java/org/jmisb/api/video/VideoDecodeThread.java, api/src/main/java/org/jmisb/api/video/VideoFileInput.java, api/src/main/java/org/jmisb/api/video/VideoInput.java, api/src/test/java/org/jmisb/api/video/DemuxReturnValueTest.java, api/src/test/java/org/jmisb/api/video/IFileEventListenerTest.java
For processing purposes, I'd like to know when I'm able to close off my output files and drop the processing loop.
Resolves #149 
Adds event listener (peer to the existing metadata event and video frame event interfaces), and wires it up. Because frames can be queued, we also need to check the queue is empty first.
I modified the viewer application with debug statements. There is a little unit testing, but its not very comprehensive given the difficulty with mocking the native code.
N/A.
=> Add end-of-file event listener

api/src/main/java/org/jmisb/api/video/VideoStreamInput.java
Implements RTSP as an input stream.
Resolves #118.
I don't fully understand the problem, but it appears that `timeout` is not a good thing for RTSP. There is such an option (https://ffmpeg.org/ffmpeg-protocols.html#rtsp) but its in seconds. By contrast, `stimeout` is in microseconds.
There is an RTSP example over at https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java that discusses the options in relation to RTSP. I'm not sure if that is meant to be a kind of bug report, or just a discussion of the workarounds. However it uses `stimeout` too.
Tested with the viewer application on a few RTSP examples I found on the internet. I tried traffic cameras, and also the "Big Buck Bunny" example.
- rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
- …
=> Add support for RTSP streams

README.md
This provides a bit more detail (and currency) on the top level README.md file. It also fixes a few markdownlint complaints.
Changed the bulleted list to a table, added some links. The status is intentionally pretty conservative, and could be made more positive in the future.
Docs only, but I reviewed in in github.
N/A
=> readme: update status, fix markdown lint

api/src/main/java/org/jmisb/api/klv/st0601/FlagDataKey.java, api/src/main/java/org/jmisb/api/klv/st0601/GenericFlagData01.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/FlagDataKeyTest.java, api/src/test/java/org/jmisb/api/klv/st0601/GenericFlagData01Test.java
Implements an item in ST0601 that we don't yet support.
Resolves #165.
Adds an IUasMetadataValue implementation, and an enumeration for the bit-level "keys".
The implementation is set up to support the nested display capability that I hope to merge soon.
Wrote new unit tests, and ran the viewer application against video that included this tag (from the MISB FLI data), and some other video that didn't include it.
*Checks were restarted, and subsequently passed*
=> st0601: implement GenericFlagData01 (item 47)

.github/workflows/qa.yml, api/pom.xml, core/pom.xml, viewer/pom.xml
We have a `dependencycheck` profile, but it isn't in the main build (because it takes a fair time to run, especially the first time each day). This adds the profile to a CI action.
Resolves #178.
Uses github actions to build on linux with the profile enabled. The profile configuration is updated to fail the build if there are any vulnerable dependencies.
Tested by updating to 5.3.2 (see #180) and running the build (with `-Pdependencycheck`), which causes a build failure.
That is verified during this PR. 
N/A.
*Note the failing QA check - that is "success" for this PR, and is resolved in #179.*
=> build: add dependency check to continuous integration

api/src/main/java/org/jmisb/api/klv/st1909/MetadataItems.java, api/src/main/java/org/jmisb/api/klv/st1909/MetadataKey.java, api/src/main/java/org/jmisb/api/klv/st1909/OverlayRenderer.java, api/src/main/java/org/jmisb/api/klv/st1909/OverlayRendererConfiguration.java, api/src/main/java/org/jmisb/api/klv/st1909/ST0601Converter.java, api/src/main/java/org/jmisb/api/klv/st1909/package-info.java, api/src/test/java/org/jmisb/api/klv/st1909/MetadataItemsTest.java, api/src/test/java/org/jmisb/api/klv/st1909/MetadataKeyTest.java, api/src/test/java/org/jmisb/api/klv/st1909/OverlayRendererConfigurationTest.java, api/src/test/java/org/jmisb/api/klv/st1909/OverlayRendererTest.java, api/src/test/java/org/jmisb/api/klv/st1909/ST0601ConverterTest.java, viewer/src/main/java/org/jmisb/viewer/MisbViewer.java, viewer/src/main/java/org/jmisb/viewer/VideoPanel.java
This is an reasonably complete implementation of ST1909 "Metadata Overlay for Visualization".
Resolves #61.
Adds a new module. Updates the viewer application to (optionally) display the visualisation.
The timestamp for metadata is MISP time, not UTC. We have existing items for that work, and I'll update the completion criteria to include this.
There are a few parts that aren't implemented - the reticle, the bounding box for next zoom, and the FT metadata. We need more ST0604 support for the FT metadata (frame timestamp). The reticle is easy for where its on Frame Center, but hard for when its on another target location. Those are all optional to implement - we can add tickets later if its important.
Reasonable level of unit testing in the `api` module. Used viewer application.
=> st1909: initial implementation

api/checkstyle_suppressions.xml, api/src/main/java/org/jmisb/api/klv/st0603/ST0603TimeStamp.java
Updates and extends javadoc in ST0603 implementation to fix checkstyle warnings.
Resolves #188
Update javadoc - two minor style fixes.
Enables warnings (removes supression) for this package.
Build / unit test only.
N/A.
=> st0603: minor javadoc style fixes

.github/workflows/qa.yml
The goal here is to check dependencies, but the IT tests are failing with
```
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.swscale
```
That might be a JDK 11 issue, but in any case its defeating the point of this workflow.
So at least for now, disable the tests.
Adds `-DskipTests` to the configuration for this workflow
Will be tested as part of this PR.
=> qa: disable tests in the QA checks

api/src/main/java/org/jmisb/api/common/IInvalidDataHandlerStrategy.java, api/src/main/java/org/jmisb/api/common/InvalidDataHandler.java, api/src/main/java/org/jmisb/api/common/LogOnInvalidDataStrategy.java, api/src/main/java/org/jmisb/api/common/ThrowOnInvalidDataStrategy.java, api/src/main/java/org/jmisb/api/klv/LdsParser.java, api/src/main/java/org/jmisb/api/klv/st0102/localset/SecurityMetadataLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0102/universalset/SecurityMetadataUniversalSet.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkMessage.java, api/src/main/java/org/jmisb/api/klv/st0903/VmtiLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0903/algorithm/AlgorithmLS.java, api/src/main/java/org/jmisb/api/klv/st0903/ontology/OntologyLS.java, api/src/main/java/org/jmisb/api/klv/st0903/vchip/VChipLS.java, api/src/main/java/org/jmisb/api/klv/st0903/vfeature/VFeatureLS.java, api/src/main/java/org/jmisb/api/klv/st0903/vmask/VMaskLS.java, api/src/main/java/org/jmisb/api/klv/st0903/vobject/VObjectLS.java, api/src/main/java/org/jmisb/api/klv/st0903/vtarget/VTargetPack.java, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/VTrackerLS.java, api/src/test/java/org/jmisb/api/common/InvalidDataHandlerTest.java, viewer/src/main/java/org/jmisb/viewer/MisbViewer.java
#143 was an earlier attempt to provide options for parsing, in the event of invalid data or other problems. It wasn't that great though. This is another approach, based on discussions with @wlfgang on gitter.
Adds singleton for invalid data handling, which delegates out to configured strategies. At the moment there are four cases - overrun, missing checksum, wrong checksum, and bad field value encoding. Adding more would be trivial.
Strategies only need to implement a one-method interface.
Viewer has been modified to log checksum and invalid values (instead of throwing).
Unit tests, plus viewer usage on some files that have issues (e.g. MISB FLI files for 0903 baseline, and the "Night Flight" that has the wrong size Target Width).
=> klv: allow different parser strategies for errors

api/checkstyle_suppressions.xml, api/src/main/java/org/jmisb/api/klv/st0806/FragCircleRadius.java, api/src/main/java/org/jmisb/api/klv/st0806/FrameCode.java, api/src/main/java/org/jmisb/api/klv/st0806/IRvtMetadataValue.java, api/src/main/java/org/jmisb/api/klv/st0806/RvtLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0806/RvtMetadataConstants.java, api/src/main/java/org/jmisb/api/klv/st0806/RvtMetadataKey.java, api/src/main/java/org/jmisb/api/klv/st0806/RvtPlatformIndicatedAirspeed.java, api/src/main/java/org/jmisb/api/klv/st0806/RvtPlatformTrueAirspeed.java, api/src/main/java/org/jmisb/api/klv/st0806/RvtString.java, api/src/main/java/org/jmisb/api/klv/st0806/ST0806Version.java, api/src/main/java/org/jmisb/api/klv/st0806/TelemetryAccuracyIndicator.java, api/src/main/java/org/jmisb/api/klv/st0806/UserDefinedTimeStampMicroseconds.java, api/src/main/java/org/jmisb/api/klv/st0806/VideoDataRate.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/AbstractRvtPoiAoiLatitude.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/AbstractRvtPoiAoiLongitude.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/IRvtPoiAoiMetadataValue.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/PoiAltitude.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/PoiAoiNumber.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/PoiAoiType.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/RvtAoiLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/RvtAoiMetadataKey.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/RvtPoiAoiTextString.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/RvtPoiLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0806/poiaoi/RvtPoiMetadataKey.java, api/src/main/java/org/jmisb/api/klv/st0806/userdefined/IRvtUserDefinedMetadataValue.java, api/src/main/java/org/jmisb/api/klv/st0806/userdefined/RvtUserDefinedLocalSet.java, api/src/main/java/org/jmisb/api/klv/st0806/userdefined/RvtUserDefinedMetadataKey.java
Fixes javadoc warnings reported by checkstyle in ST0806.
Resolves #191. 
Removes suppression for these packages.
Fixes the style warnings and adds missing javadoc on methods.
Full build with unit test runs.
=> st0806: javadoc cleanups

.github/workflows/jdk11.yml
During some previous work, the QA tests failed for things unrelated. I think that could be JDK11 related.
This change adds JDK11 to the CI to make sure its all OK.
Resolves #207  
Adds a github workflow using the default JDK on Ubuntu 20.04 (which is mean to be JDK11)
Testing as part of this draft PR.
N/A.
=> ci: add JDK11

api/src/main/java/org/jmisb/api/video/VideoFileInput.java
While working on a command line example, I couldn't seem to make the playing thread terminate. This changes the timeout for the `thread.join()` to be 2000 (milliseconds). Otherwise it just seems to wait indefinitely.
Adds timeout
Command line test code, plus viewer application. Doesn't really lend itself to unit testing.
=> video: add timeout for thread join

api/src/main/java/org/jmisb/api/klv/st1909/ST0601Converter.java, api/src/test/java/org/jmisb/api/klv/st1909/ST0601ConverterTest.java
ST1909 includes a north arrow group, with how to determine north being implementation dependent. We previously supported working it out from the angles of the left and right sides (based on offset corner coordinate items). However not all files include those, and MISB would actually prefer Full Corner Coordinates (ST 0601 Items 82-89) over offsets (Items 26-33).
This PR adds support for full coordinates, while continuing to support offsets.
Resolves #217 
Adds an additional code path for full coordinates.
There is a small change to the offset path as well, based on a glitch I noted (where it "flips" 180, then back) on the full coordinates. 
Mostly viewer - a lot of staring at the arrow.
Includes one unit test.
=> st1909: add support for north arrow from full corners

api/fuzzing.md, api/src/main/java/org/jmisb/api/klv/st0102/DeclassificationDate.java, api/src/test/java/org/jmisb/api/klv/st0102/DeclassificationDateTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/LocalSetFactoryFuzzTest.java
A recent change added fuzzing for ST0601. This change uses the same infrastructure to allow fuzzing of ST 0102 security local set.
Resolves #225 
Adds a fuzz target for the `createValue()` factory. Updates fuzzing.md to document that.
Fixes one fuzz problem found.
Ran the fuzzer.
Added a unit test matching the fuzzing problem found in DeclassificationDate.
=> st0102: add fuzzing for local set

api/fuzzing.md, api/src/main/java/org/jmisb/api/klv/st0903/vtracker/TrackId.java, api/src/test/java/org/jmisb/api/klv/st0903/VmtiLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/algorithm/AlgorithmLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/ontology/OntologyLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vchip/VChipLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vfeature/VFeatureLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vmask/VMaskLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vobject/VObjectLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtarget/VTargetPackFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtarget/VTargetPackTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackItemFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackLocalSetFuzzTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/TrackIdTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/VTrackerLSTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtracker/VTrackerLocalSetFuzzTest.java, core/src/main/java/org/jmisb/core/klv/UuidUtils.java
This continues the recent work on adding fuzzing targets to include ST0903.
Resolves #226 
Adds fuzzing targets and documentation for the main entry points into ST0903.
Fixes one fuzzing issue in core, where malformed input in UUID parsing could cause an out-of-bounds array index.
Ran the fuzzer for at least 5 minutes on each new target. Added unit tests for problems.
=> st0903: Add fuzzing targets for ST0903 VMTI and VTrack LS

api/src/main/java/org/jmisb/api/klv/st0102/ObjectCountryCodeString.java, api/src/test/java/org/jmisb/api/klv/st0102/ObjectCountryCodeStringTest.java
ST0102 has a mix of string encodings. The Object Country Code is meant to be UTF-16 Big Endian. However some producers just put ASCII (equivalent to UTF-8 for this purpose) in there. This PR provides a workaround based on the usual case being a single country, and the minimum length of a country code being 2 characters (4 bytes in UTF-16). So if the byte length is < 4, we're probably dealing with ASCII.
Resolves #233.
Adds a check to the ST0102 ObjectCountryCodes implementation to check length and output a warning, then decode as UTF-8.
Adds a corresponding unit test to check the result, including the logger warning.
Checks that the output (`getBytes()`) is still UTF-16.
Unit test.
Ran viewer on some known-good files (MISB), and some known-bad files (the klv_metadata_test_async.ts and …
=> st0102: work around incorrect ObjectCountryCodes encoding

api/src/main/java/org/jmisb/api/klv/IMisbMessageFactory.java, api/src/main/java/org/jmisb/api/klv/KlvParser.java, api/src/main/java/org/jmisb/api/klv/MisbMessageFactory.java, api/src/main/java/org/jmisb/api/klv/eg0104/PredatorUavMessageFactory.java, api/src/main/java/org/jmisb/api/klv/st0102/localset/SecurityMetadataLocalSetFactory.java, api/src/main/java/org/jmisb/api/klv/st0102/universalset/SecurityMetadataUniversalSetFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkMessageFactory.java, api/src/main/java/org/jmisb/api/klv/st0808/AncillaryTextLocalSetFactory.java, api/src/main/java/org/jmisb/api/klv/st0903/vtrack/VTrackLocalSetFactory.java, api/src/test/java/org/jmisb/api/klv/KlvParserTest.java, api/src/test/java/org/jmisb/api/klv/UniversalLabelTest.java, api/src/test/java/org/jmisb/api/klv/eg0104/PredatorUavMessageFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/SecurityMetadataLocalSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0102/universalset/SecurityMetadataUniversalSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0808/AncillaryTextLocalSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackLocalSetFactoryTest.java, examples/README.md, examples/parserplugin/README.md, examples/parserplugin/nbactions.xml, examples/parserplugin/pom.xml, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/Main.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/MetadataPlayer.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/timemessage/ITimeMessageValue.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/timemessage/PrecisionTimeStamp.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/timemessage/TimeMessage.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/timemessage/TimeMessageConstants.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/timemessage/TimeMessageFactory.java, examples/parserplugin/src/main/java/org/jmisb/examples/parserplugin/timemessage/TimeMessageKey.java, examples/pom.xml
As discussed in #241, it would be useful to be able to plug in additional handlers. The API extension for that also provides an opportunity to clean up a chain of `if(...)` calls.
Adds a factory interface, and factories for each of the affected top level message implementations.
Also adds an example showing how to use it externally.
Unit tests.
Ran viewer on some test data to make sure basic parsing is still OK.
Ran example on test data that has the non-standard structure.
N/A.
=> klv: use factories to isolate KlvParser from message implementation

api/src/main/java/org/jmisb/api/klv/st0808/AncillaryTextLocalSet.java
Fixes a minor cut-n-paste issue in the ST0808 javadocs.
No code changes, just the docs.
N/A.
=> st0808: fix minor javadoc issue

api/src/main/java/org/jmisb/api/klv/st0102/CcmDate.java, api/src/main/java/org/jmisb/api/klv/st0102/DeclassificationDate.java, api/src/main/java/org/jmisb/api/klv/st0102/OcmDate.java
We have comments that are TODO items about avoiding a string allocation.
I had a look at alternatives to String for `LocalDate.parse()`, and while it can potentially take
any CharSequence, those require char[] and we're working from UTF-8 byte[].
In addition, the implementation of `LocalDate.parse()` ends up calling into a method that calls
`toString()` on the input text, so its not going to save us anything.
Just remove the comment. There are no code changes.
Ran unit tests.
=> chore: remove TODO comment

api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackLocalSetTest.java
For reasons I can't recall, I left a TODO item in one of the VTrack tests.  This PR fixes that.
Replaces some commented-out code and removes the TODO. Only affects test code.
Updated the test, re-ran all the unit tests.
N/A
=> fix: update VTrack test case

examples/gstsink/src/main/java/org/jmisb/examples/gstsink/Main.java
There was some follow-up discussion on https://github.com/WestRidgeSystems/jmisb/pull/240 where neilcsmith-net pointed out an implementation error in the gstreamer example.
Reworks the code to implement the required `unmap()` call.
No testing, although the fix is concurred by the original reporter, and he's the java gstreamer lead, so I'm feeling OK with it.
N/A.
=> example(gst): add missing GST buffer unmap()

api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackFullParseTest.java
There were a few TODO items left in the VTrack full parse test. This completes the test and removes the TODO items.
I checked through the list of item in ST0903 VTrackItem Pack (Table 19) and there were three items not fully covered:
- frameHeight
- miisId
- acceleration
Frame height was sort-of being tested, but was out of order and the existence test was wrong (dupe of frameWidth). Moved / fixed.
Acceleration was in the data, but wasn't being checked.Now checked.
miisId wasn't covered. Added to the data (with updates to the nested lengths) and added to the checks.
Just re-ran unit tests.
N/A
=> st0903: complete full parse test for VTrack

api/pom.xml, core/pom.xml, examples/gstsink/pom.xml, pom.xml, viewer/pom.xml
There is increasing interest in Software Bill Of Materials (SBOM). There are multiple competing formats, but one popular one seems to be CycloneDX. This adds automated generation of the SBOM in JSON and XML formats.
Adds a maven plugin and configuration for the core, api and viewer modules.
Also picks up a few dependency upgrades, which showed up during analysis checks.
Full build, ran the viewer app against a few test files.
Also did a quick check on the GST example.
=> feat: add SBOM support for key modules

api/pom.xml, core/pom.xml, viewer/pom.xml
#254 added Software Bill of Materials (SBOM) support. Unfortunately, that appears to have slowed down the build for our key modules (e.g. core and api), which is #255. 
The fix is to generate a plain `bom` instead of `aggregateBom`. The only change is in the POMs.
I manually inspected the resulting XML and JSON files. The results are pretty much what I expected, although I'm very new at SBOM.
Timing is objectively better. The aggregate results are in #255, and show the core, api and viewer modules taking around 70 seconds longer (each) than they did before the Cyclone DX maven modules were added in #254. 
Building with CycloneDX modules disabled (`mvn clean install -Dcyclonedx.skip=true`) now looks like:
```
[INFO] Reactor Summary for jMISB 1.11.0-SNAPSHOT:
[INFO] 
[INFO] jMISB …
```
=> fix: use BOM instead of aggregate for SBOM

api/src/main/java/org/jmisb/api/klv/st0601/ImageHorizonPixelPack.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkFactory.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/ImageHorizonPixelPackTest.java
Implements ST0601 Tag 81 "Image Horizon Pixel Pack". This is one of the few remaining tags we don't currently support.
There was an open issue about how it was encoded (i.e. literal value, or mapped from 0...100% to 0...255), that was discussed at the last MISB meeting and resolved as literal value. I expect to see that as a draft ST0601.17 soon.
It is a fairly standard IUasDatalinkValue implementation. The unpacking and packing cases are slightly complicated because of the floating length pack, but not much different other than that.
Unit tests only. I'm not aware of any sample data for this - it doesn't seem like its very widely implemented.
*I'm leaving this as a WIP pending seeing the updated ST0601.17 which I expect to have new test values.*
=> st0601: add Image Horizon Pixel Pack support

api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java
Trivial fix for a warning I inadvertently introduced in #164.
Just updates the javadoc to end in a full stop.
Regenerated the javadoc as part of a build.
N/A.
- [N/A] I have added tests to cover my changes.
=> fix: correct javadoc for horizon pixel pack tag

api/src/test/java/org/jmisb/api/klv/st0601/PayloadIdentifierKeyTest.java, api/src/test/java/org/jmisb/api/klv/st0903/AlgorithmIdentifierKeyTest.java, api/src/test/java/org/jmisb/api/klv/st0903/OntologyIdentifierKeyTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtarget/TargetIdentifierKeyTest.java
There is a warning about deprecated API use in one of the ST 0903 tests. Its caused by a pointless `new Integer(2)` that was deprecated in Java 9 (see https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html#%3Cinit%3E(int)), and isn't required.
Updates code in four tests to avoid this call. No change to production code.
Re-ran all the unit tests as part of a build.
N/A.
=> chore: remove deprecated API use from 0601/0903 tests

miml-maven-plugin/src/main/resources/templates/itemKeyTest.ftl
This is analogous to the #263 changes, but I didn't notice it until both that was fixed, and MIMD was merged.
It switches a test from using deprecated `new Integer(...)` to `new String()`. The test is just doing Object class comparison, and it doesn't really matter what the actual thing we're comparing it to is, as long as it is different to the class being tested.
No changes to production code.
Re-ran the tests as part of a full build.
N/A.
=> fix: remove deprecated API use in MIMD tests

api/src/main/java/org/jmisb/api/klv/st1303/MDAPDecoder.java, api/src/main/java/org/jmisb/api/klv/st1303/NaturalFormatEncoder.java, api/src/test/java/org/jmisb/api/klv/st1303/MDAPDecoderTest.java, api/src/test/java/org/jmisb/api/klv/st1303/NaturalFormatEncoderTest.java
We have most of what we need from ST 1303 (array encoding) for MIMD and ST 1206, but coverage isn't too good on other aspects, especially on 1D signed integer, and some other natural format encoding. I'm working down the list in preparation for future MIMD and some of the lesser-used formats which potentially need this.
Relates to #198, but doesn't complete it.
Adds encoding for:
- 1D signed integer in natural format
- 2D unsigned integer in natural format
- 2D boolean in natural format
Adds decoding for:
- 1D signed integer in natural format
Fixes some minor issues and test naming in existing code.
Re-ran unit tests as part of full build.
N/A.
=> st1303: add more natural format encoding support

api/pom.xml, core/pom.xml, examples/generator/pom.xml, examples/gstsink/pom.xml, examples/mimdgenerator/pom.xml, examples/movingfeatures/pom.xml, examples/parserplugin/pom.xml, examples/pom.xml, examples/systemout/pom.xml, miml-maven-plugin/pom.xml, pom.xml, viewer/pom.xml
Much like the automatic code formatting plugin, this change adds automatic formatting for the Maven poms. I became aware of this based on use in GeoServer.
The formatting / sort order is fairly flexible. Its also possible to define your own. I went with the Maven recommended profile, and switched on 4 spaces (default is 2, but we mostly use 4 in the existing pom files and that matches the Java convention).
See https://github.com/Ekryd/sortpom/wiki/Parameters and https://github.com/Ekryd/sortpom/wiki/PredefinedSortOrderProfiles
for more options. Happy to discuss further or for you to make changes.
Adds a plugin, reformats the existing pom.xml files.
Did a full rebuild, looked at the revised code.
=> add pom formatting

viewer/pom.xml
Looks like there was a bad merge in the latest round of PRs, which prevents maven from building.
Adds model version back into viewer POM, along with XML header.
Full build.
N/A.
=> repair viewer POM after merge

api/src/main/java/org/jmisb/api/klv/st0601/WaypointList.java
This resolves two instances of "Implicit cast of source type int to narrower destination type byte." warnings reported by LGTM.
The source was a static `int` value, changed that to be `byte`.
Unit testing only. The changed code is in WaypointList, which I don't have any real data for.
N/A.
=> fix(st0601): avoid implicit narrowing of integer result

viewer/src/main/java/org/jmisb/viewer/map/SensorFootprintPainter.java
I used an `Integer` as the "footprint" corner counter in the viewer map. LGTM complains that its unnecessary.
Switched to `int`, and generated the String representation of that using `Integer.toString(int)`. 
Full rebuild, and tested that corners still render correctly in the viewer.
N/A.
=> fix(map): avoid using Integer as a counter

api/src/main/java/org/jmisb/api/klv/st0601/PositioningMethodSource.java
LGTM produces a warning that the use of `Boolean` in the ST 0601 PositioningMethodSource implementation is not required.
Simple replacement with use of `boolean`.
Unit testing only. I don't have real data that uses this tag.
N/A.
=> fix(st0601): avoid unnecessary boxing in PositioningMethodSource impl

api/src/main/java/org/jmisb/api/klv/BerDecoder.java
LGTM complains that the BER length can never be `< 1`. I've checked the code, and agree. I normally like to have this kind of sanity check, but in this case its probably worth removing considering the amount of BER decoding we do.
Just removes that part of the check.
Full build.
=> fix(klv): remove test that is always false

core/src/main/java/org/jmisb/core/video/FrameConverter.java, core/src/test/java/org/jmisb/core/video/FrameConverterTest.java
LGTM complains that the multiplication in this line:
```
ByteBuffer src = frame.data(0).capacity(frame.width() * frame.linesize(0)).asBuffer();
```
can overflow (because the `linesize` and `width` are `int` so the multiplication result is an `int`, even though `capacity()` takes a `long` argument).
We are unlikely to handle such large results (because BufferedImage will likely probably fail), but its worth protecting our own code.
Cast to `long` before the multiplication. 
Also adds some tests, although I couldn't get to cause the overflow, so they're just checking the normal path.
Unit testing as part of a full build.
I also ran up the viewer application for a quick check.
N/A.
=> core(video): use long for data buffer calcs

miml-maven-plugin/src/main/java/org/jmisb/maven/CodeGeneratorListener.java
Fixes a resource leak (closing FileOutputStream) in the MIML generator plugin. This is a flaw reported by LGTM.
Changed to try-with-resources, which is clearly what I should have done in the first place.
Just did a full build.
=> miml-plugin: fix resource leak in file writing

miml-maven-plugin/pom.xml, pom.xml
During #281 / #282 investigation, I noted that the dependency check plugin managed to get reverted from 6.1.5 to 6.1.2 during the maven formatting merge. 
On updating that, I found some new dependency issues in the MIML maven plugin. This updates the dependency check plugin to an even newer 6.1.6, and updates the dependencies for the MIML maven plugin module.
Updates versions in relevant pom files. Removes some unused (`test` scoped) dependencies. The pinning of commons-io is a bit unfortunate, but the CVE is new and there isn't a released parent version that is new enough.
Also, I had to split the maven versioning defines, otherwise the version of maven used to build it also needs to match latest.
Full build.
=> fix(miml-maven): update MIML maven plugin dependencies

api/src/main/java/org/jmisb/api/klv/st1204/CoreIdentifier.java
Another LGTM warning about boxing primitive types. This one affects the CoreId parsing.
Simple replacement of `Integer` with `int`.
N/A.
=> fix(st1204): avoid unneeded boxing of core id version

viewer/src/main/java/org/jmisb/viewer/MisbViewer.java
Resolves #287 
Only affects viewer logic. Ensures that when a stream (e.g. UDP, although I have SRT in work too) is opened in the UI, any existing `videoInput` sources are closed.
Manual viewer tests.
Tested the problem case (file -> stream).
Tested just opening a stream (i.e. no currently open file).
N/A.
=> viewer: close previous input when opening stream

.github/workflows/jdk11.yml, .github/workflows/qa.yml
The failing PR thing is annoying and requires manual retry. I can only do that by closing and re-opening the PR (can't restart a single job). 
Some failures are really transient, and do not represent problems in jmisb - the "failed to transfer artifact" problem is a good example. In that case, a retry is the right thing to do.
Changes the JDK11 and QA builds to retry the build step if they fail, up to three times.
Also changes the QA build to just `verify`(rather than `install`) since the packaging part is irrelevant for that.
Only affects the workflow, so testing needs to be online.
=> ci: retry linux and qa builds on failure

examples/mimdgenerator/src/main/java/org/jmisb/examples/mimdgenerator/Generator.java
Fixes a deprecated API warning during compilation. Its better if the examples show good usage of the API, and this one is a bit dated.
Updates the constructor usage to be explicit about the required format. Only affects that one example.
Ran the MIMD generator, and tested the output still works in the viewer application.
N/A.
=> mimdgenerator: fix deprecated API usage

miml-maven-plugin/src/main/java/org/jmisb/maven/CodeGeneratorListener.java
The MIML Maven plugin is pretty verbose. That was useful when I was less confident on it, but its now masking other stuff, and isn't appropriate.
Remove output.
Full build.
=> miml: avoid verbose logging

pom.xml, viewer/src/main/java/org/jmisb/viewer/map/SensorFootprintPainter.java, viewer/src/main/java/org/jmisb/viewer/map/SensorLocationPainter.java
There are a couple of cases of unchecked class usage in the map part of the viewer application.
They were being flagged by the compiler, but not identified.
Add the `unchecked` lint flag to the compiler (at the top level, to help with this should it happen again), and fix the unchecked usage.
Full compile with unit tests.
Ran viewer application and checked the painting of footprint and sensor location is still OK.
=> viewer: fix unchecked usage

api/src/main/java/org/jmisb/api/video/VideoOutput.java
After cleanup of the MIML output, it was easier to see warnings. This one seemed minor, but was trivial to fix.
Adds one `@param` javadoc entry.
Full build.
=> api: minor javadoc update

api/src/main/java/org/jmisb/api/klv/st0601/ControlCommands.java, api/src/main/java/org/jmisb/api/klv/st0601/ControlCommandsKey.java, api/src/main/java/org/jmisb/api/klv/st0601/ISpecialFraming.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkMessage.java, api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkTag.java, api/src/test/java/org/jmisb/api/klv/st0601/ControlCommandTest.java, api/src/test/java/org/jmisb/api/klv/st0601/ControlCommandsKeyTest.java, api/src/test/java/org/jmisb/api/klv/st0601/ControlCommandsTest.java
Resolves #140
The Control Command pack can be repeated in a single ST 0601 local set. We don't currently support that, and will overwrite any earlier entries with the last encountered entry. This is currently tracked as #140.
Adds a "holder" class to capture each entry. Its not really clean because of how we serialise out the entries as shown in https://github.com/WestRidgeSystems/jmisb/blob/develop/api/src/main/java/org/jmisb/api/klv/st0601/UasDatalinkMessage.java#L138-L145
I've introduced a special "marker" interface to handle the special case. Currently this is the only class that implements it, but there are more coming (we just don't implement that functionality yet). There are other ways to do this, but this seemed a way to avoid changing existing code everywhere.
=> st0601: add support for multiple Control Command entries

api/src/test/java/org/jmisb/api/klv/st0601/CountryCodesTest.java
This is a low-priority PR to add some missing test coverage for one class in the ST 0601 implementation
Adds one unit test for the `CountryCodeKey` class.
Ran build to execute unit tests, and verified improved coverage through jacoco report.
=> st0601: add trivial unit test for CountryCodeKey

.github/workflows/jdk11.yml, .github/workflows/jdk14.yml, .github/workflows/jdk8.yml
After Travis CI dropped out, we no longer have a JDK 8 build, and coveralls no longer works (last update was April).
Also, as JDKs move along, it is probably worth testing on JDK 14.
Resolves #301 
Adds an Ubuntu 18.04 + JDK 8 to GH actions.
Adds an Ubuntu 20.04 + JDK 14 to GH actions.
Adds codecov.io (instead of coveralls) to the actions.
Only as part of this PR.
=> ci: add JDK 8 and JDK 14 builds

api/SpotBugsFilter.xml, core/SpotBugsFilter.xml, core/pom.xml, miml-maven-plugin/src/main/java/org/jmisb/maven/ClassModel.java, miml-maven-plugin/src/main/java/org/jmisb/maven/EnumerationModel.java, miml-maven-plugin/src/main/java/org/jmisb/maven/Models.java, pom.xml
This updates the version of spotbugs we're using from 4.0.2 (release April 2020) to 4.3.0 (most recent release - 1 July 2021). The maven plugin is also updated. This is just routine maintenance, no specific motivating feature.
Update versions. 4.3.0 adds new checks for exposing the internal representation of an object. However fixing that mostly involves copying objects, and I don't want to pay that penalty in general. I'm OK with fixing it for the code generator, but otherwise I'm suppressing the bug. Also, the viewer application actually relies on being able to mutate some of the values for the map display. 
Ran full build, including all unit tests.
Checked the viewer application is still OK.
N/A.
=> update spotbugs checks and fix / suppress issues

examples/README.md, examples/pom.xml, examples/rawklv/README.md, examples/rawklv/pom.xml, examples/rawklv/src/main/java/org/jmisb/examples/rawklv/Main.java, examples/rawklv/src/main/java/org/jmisb/examples/rawklv/MetadataPlayer.java, examples/rawklv/src/main/java/org/jmisb/examples/rawklv/PrintOnInvalidDataStrategy.java
While doing some interoperability testing with the MISB and ranges team, I needed to test raw (not TS multiplexed) KLV dumping. We don't have an example of that, although there is some discussion in various MISB documents about KLV as a separate feed (e.g. VMTI metadata only) and we do have support for it.
Adds a very simple example of parsing and displaying raw KLV. It is based on the systemout example.
No functional changes to the "real" code.
Ran it on some MIMD test data provided by the MISB.
Also did a full build.
=> examples: add example to decode and display raw KLV

.gitignore, api-ffmpeg/pom.xml, api/pom.xml, core/pom.xml, elevation/geoid/pom.xml, miml-maven-plugin/pom.xml, viewer/pom.xml
The SBOM generation seems useful, but is more applicable to releases than every build. Its slowing down the build for limited value.
Uses the existing release profile to invoke the previously unconditional SBOM generation.
Ran it with and without the profile, seems OK.
=> build: move sbom creation to release profile

api-ffmpeg/src/main/java/module-info.java, api/src/main/java/module-info.java, api/src/test/java/org/jmisb/api/klv/st0102/localset/SecurityMetadataLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st0102/universalset/SecurityMetadataUniversalSetTest.java, api/src/test/java/org/jmisb/api/klv/st0806/RvtLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st0808/AncillaryTextLocalSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0808/AncillaryTextLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st0903/VmtiLocalSetOneWithTheLotLegacyModeTest.java, api/src/test/java/org/jmisb/api/klv/st0903/VmtiLocalSetOneWithTheLotTest.java, api/src/test/java/org/jmisb/api/klv/st0903/VmtiLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackLocalSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st0903/vtrack/VTrackLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st1108/InterpretabilityQualityLocalSetFactoryTest.java, api/src/test/java/org/jmisb/api/klv/st1108/st1108_2/LegacyIQLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st1108/st1108_3/IQLocalSetTest.java, api/src/test/java/org/jmisb/api/klv/st1206/SARMILocalSetTest.java, core/src/main/java/module-info.java, elevation/geoid/src/main/java/module-info.java, examples/cotconverter/pom.xml, examples/cotconverter/src/main/java/module-info.java, examples/cotconverter/src/main/java/org/jmisb/examples/cotconverter/Converter.java, examples/generator/src/main/java/module-info.java, examples/gstsink/src/main/java/module-info.java, examples/mimdgenerator/src/main/java/module-info.java, examples/movingfeatures/src/main/java/module-info.java, examples/parserplugin/src/main/java/module-info.java, examples/rawklv/src/main/java/module-info.java, examples/systemout/src/main/java/module-info.java, viewer/src/main/java/module-info.java
Java 11 compatibility really needs support for the modules system (JSR 376). This PR adds that.
A couple of problems with visibility that have been corrected.
Some changes in the CoT converter to clean up logging.
This doesn't do refactoring to remove the AWT dependency (java.desktop module).
That seems more intrusive and will be done as a separate commit.
I assume this could be breaking for existing Java 11 users, since the names of the modules will not longer match what was previously generated.
Full rebuild to exercise all unit tests.
Viewer application.
Each example app (some where only validated to "it runs" level, such as CoT converter - I assume if the XML comes out as UDP traffic, then the content is still OK). Note that since we don't have the GPL part enabled in 2.x branch at …
=> 2.x: migrate to java modules

api/src/main/java/org/jmisb/api/klv/st1206/ISARMIMetadataValue.java, api/src/main/java/org/jmisb/api/klv/st1206/MinimumDetectableVelocity.java, api/src/main/java/org/jmisb/api/klv/st1206/ReferenceFrameRangeLayoverAngleRelativeToTrueNorth.java, api/src/main/java/org/jmisb/api/klv/st1206/package-info.java, api/src/test/java/org/jmisb/api/klv/st1206/MinimumDetectableVelocityTest.java
During development of another set, I noted a bit of incomplete documentation on the ST 1206 set. Looks like I just didn't pay enough attention to the javadoc at the time.
Also found a method that was mis-named (cut-n-paste error).
Minor updates to the javadoc and one method. The method renaming required test changes.
Just a full build and inspection of the resulting documentation.
N/A.
=> st1206: minor cleanups for method name and docs

README.md
The old page is 404.
The GWG is migrating all the focus group home pages. The old pages are gone (probably permanently).
Updates readme link to new page. Also removed one trailing whitespace entry.
N/A.
=> doc: update MISB home page link (2.x)

pom.xml
Patch-level upgrade to jackson-databind (which brings in some other jackson dependencies too). The changes are shown in https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13.1
We don't use this much - some testing data that was convenient to make in JSON format, and one example for making OGC Moving Features. However its probably worth keeping up.
Just bumped the version in managed dependencies.
Full build to ensure the tests still work, and ran the moving features example with some VMTI data. Seemed OK.
=> deps: upgrade jackson-databind to 2.13.1 (2.x)

api/src/main/java/org/jmisb/api/klv/st0903/vmask/BitMaskSeries.java, api/src/test/java/org/jmisb/api/klv/st0903/VTargetSeriesTest.java
Adds a check in the BitMaskSeries part of ST 0903 VMask for invalid values. This came up during some fuzz testing.
Relates to #363 (resolves it for the 2.x branch, but not develop).
Additional check, so we throw KlvParseException. Includes tests replicating the fuzz results.
Unit testing only. I don't have any data that uses this part of ST 0903.
=> st0903: harden BitMaskSeries parsing (2.x)

api/src/main/java/org/jmisb/api/klv/st0903/vmask/BitMaskSeries.java, api/src/test/java/org/jmisb/api/klv/st0903/VTargetSeriesTest.java
Adds a check in the BitMaskSeries part of ST 0903 VMask for invalid values. This came up during some fuzz testing.
Resolves #363 (along with #364, which resolves it for the 2.x branch)
Additional check, so we throw KlvParseException. Includes tests replicating the fuzz results.
Unit testing only. I don't have any data that uses this part of ST 0903.
=> st0903: harden BitMaskSeries parsing (develop)

api/src/main/java/org/jmisb/api/klv/st1108/st1108_3/CompressionLevel.java, api/src/main/java/org/jmisb/api/klv/st1108/st1108_3/metric/MetricName.java, api/src/main/java/org/jmisb/api/klv/st1108/st1108_3/metric/MetricParameters.java, api/src/main/java/org/jmisb/api/klv/st1108/st1108_3/metric/MetricVersion.java
MISB has a slightly complicated definition of "utf8" type in ST 0107, which I implemented as part of the ST 0809 implementation. However I need to go back over existing places where I just used a plain String. 
This is part of the rework, covering ST 1108.
Changes most of the uses of `utf8` in ST 1108. There is one that is slightly messy, and is unlikely to trigger the special null case, so I'm going to ignore that for now.
Just a full build - no test data for this message.
=> st1108: use Utf8String class

.github/workflows/jdk11.yml
Codecov provides reporting for some modules, but not all of them. In particular, we're generating coverage for the MIML plugin (which isn't very important) and api-awt, but not uploading that. This enables uploading of api-awt jacoco reporting.
MIML might be useful later.
Updates JDK 11 github workflow CI action to upload the relevant test report. Its basically copy-n-paste from the equivalent api step.
Only on GH workflow run.
=> ci: add api-awt to codecov reporting

pom.xml
This is a micro version upgrade on a maven plugin. The release is part of the maven-plugin-tools release, see https://lists.apache.org/thread/lq00sgpx6wn322xbgts6tzdym7yzrg0z for the release notes (its not clear what happened to 3.6.3 - I had a scan of the mailing list, but didn't see anything).
There isn't anything in here that affects us - we only use the annotations for the MIML plugin.
Updates version in managed dependencies.
Full build only. Since this is only used for maven plugin at compile time, I think that is sufficient.
=> deps: version bump on maven annotations plugin to 3.6.4

api/src/main/java/org/jmisb/api/klv/UdsParser.java, api/src/test/java/org/jmisb/api/klv/UdsParserTest.java, st0602/src/main/java/org/jmisb/st0602/AnnotationMetadataUniversalSet.java, st0602/src/test/java/org/jmisb/st0602/AnnotationMetadataUniversalSetTest.java
This corrects a bug in Universal Set parsing, when the offset (usually the top level UL + the overall length) is at least as large the last key+length+value length. 
Relates to #396 (this is the 2.x part)
Update implementation to match API description.
Added unit tests at UDSParser and ST 0602 levels.
Verified in viewer with the annotation generator output.
=> 2.x: ensure UDS parsing gets all parts

api/src/main/java/org/jmisb/api/klv/UdsParser.java, api/src/test/java/org/jmisb/api/klv/UdsParserTest.java
This corrects a bug in Universal Set parsing, when the offset (usually the top level UL + the overall length) is at least as large the last key+length+value length.
Resolves #396
Update implementation to match API description.
Added unit test for `UdsParser`.
Most of the testing was against the 2.x branch (see #397)
N/A.
=> klv: fix Universal Set parsing with offsets

.github/workflows/jdk17.yml
JDK 14 is out-of-life, and JDK 17 is the current LTS. 
Also, #403 reports a problem with JDK 14. That might be a broader issue, but can be investigated better if we have a more recent JDK in the CI mix.
Add JDK 17 CI workflow. JDK 14 remains for the purposes of debugging, so this is considered to relate to #403, but not resolve it yet.
Only testing as part of the CI for this PR.
=> ci: add JDK 17 and Ubuntu 22.04 support

api-ffmpeg/src/test/java/org/jmisb/api/video/VideoFileInputOutputIT.java
This is an attempt to resolve CI problems as reported at #403.
I'm not sure I understand the root cause, but its now happening pretty reliably, so possibly this is a useful workaround.
Pre-load the required class using extant javacpp-presets capability.
Ran it locally, no problems. Will check behaviour with CI.
=> ffmpeg: pre-load required files in integration tests

pom.xml
Updates jackson-databind to latest (2.13.4) version. Changes are identified at https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13.4 - nothing we need, just maintaining current.
Update version in managed dependencies. No code changes.
Full build with unit tests (since we use it in api module tests).
Ran moving features example (since that is the other place we use it, for JSON generation). 
Both OK - no issues noted.
=> chore: bump jackson-databind to 2.13.4

api/src/main/java/org/jmisb/api/klv/ArrayBuilder.java
During work on #428, I noted a javadoc warning (missing a trailing full stop on the first line).
Add one full stop (period) character.
Build  checked, no more warning.
=> docs: minor javadoc fix

pom.xml
2.x CI is failing with a QA check for a vulnerable dependency. I don't think we are exposed to it, but its worth fixing.
Update `jackson-databind` in managed dependencies. Use of 2.14.0-rc1 is undesirable, but 2.14.0 isn't released yet.
Full build, including unit tests (which is one place we use Jackson).
Ran moving features example (which is the other place we use it).
Both OK.
=> chore: bump Jackson Databind to 2.14.0-rc1

dependency-check-suppression.xml, miml-maven-plugin/pom.xml, viewer/pom.xml
The dependency check (in QA CI build) is providing false positives for use of Apache Commons (that do not line up with the package that the CVE is against).
This is discussed in https://github.com/jeremylong/DependencyCheck/issues/5121
I have a similar fix for the 2.x branch in as part of https://github.com/WestRidgeSystems/jmisb/pull/436
Add suppression as proposed by the Dependency Check maintainers.
Full build. This is only a compile time check, so I think that is reasonable.
- [N/A] I have added tests to cover my changes.
=> qa: add suppression for false positive on Apache commons

api/src/main/java/org/jmisb/api/common/KlvParseException.java, api/src/main/java/org/jmisb/api/klv/BerDecoder.java, api/src/main/java/org/jmisb/api/klv/KlvParser.java, api/src/test/java/org/jmisb/api/klv/BerDecoderTest.java, api/src/test/java/org/jmisb/api/klv/KlvParserTest.java, dependency-check-suppression.xml, pom.xml
#442 - reference issue.  This is just a WIP attempt to provide InputStream parsing in KlvParser.
Added the below method to KlvParser.  
```java
public static void parseStream(
InputStream is,
Consumer<IMisbMessage> handler,
Consumer<KlvParseException> exceptionHandler)
```
Given that `parseBytes()` throws a KlvParseException on bad data, and when dealing with a stream, you may want the ability to continue processing, this required the ability to emit IMisbMessage and/or KlvParseExceptions without breaking the stream.
I tested with a mock application I'm developing where ffmpeg is running externally and its outputting the KLV data stream to stdout, which is being processed by KlvParser.
=> #442 - Add KlvParser.parseStream(InputStream)

dependency-check-suppression.xml, pom.xml, st1601/src/test/java/org/jmisb/st1601/GeoRegistrationKeyTest.java
During work on another local set, I noticed that there was a broken test in ST 1601 (i.e. it couldn't have passed). That wasn't being run, because it was missing the `@Test` annotation. Several other unit tests in the same test class were also missing that annotation.
The original version of this PR failed dependency checks for https://nvd.nist.gov/vuln/detail/CVE-2021-4277 which is completely unrelated to anything we use - its a broken NVD entry. There is an updated version of the OWASP dependency
check plugin that suppresses that entry. Upgrading also brought in a fix for a previous false positive (https://github.com/jeremylong/DependencyCheck/issues/5121) and we no longer need our own suppression for that.
Added missing annotations and fix the broken test. There is no code changes - …
=> st1601: fix missing @Test annotations

dependency-check-suppression.xml, pom.xml
#448 failed QA checks for reasons unrelated to the actual change. Its hitting the same false-positive for "anything utils" that we hit on 2.x in #449.
This fix is equivalent to the dependency check upgrade part of #449, but for main.
Bump dependency-check-plugin to 8.0.1, which brings in suppression for the false positive. 8.0.1 also includes a suppression for the false-positive we were previously suppressing ourselves, so that gets removed.
Full build with the dependency check profile.
=> deps: update dependency check plugin to 8.0.1

pom.xml
keeps build working on ARM macOS
Fixes #448 
Bumps the version of ffmpeg-platform to the latest one that works on macOS ARM machines.
Ran the standard test suite via `mvn install`. Also manually ran the example viewer on some MISB mpeg files. Only tested on macOS Ventura 13.1 on an M1 (ARM) Mac with JDK OpenJDK (Zulu 11, zulu11.60.19-ca-jdk11.0.17-macosx_aarch64).
=> deps: bump ffmpeg-platform to 5.1.2-1.5.8 (#448)
